package chat;


/**
* chat/_MessagerieStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../app.idl
* mardi 22 septembre 2026 22 h 30 EAT
*/


// Servi par le serveur C++ : verifie, stocke en MySQL et notifie les abonnes
public class _MessagerieStub extends org.omg.CORBA.portable.ObjectImpl implements chat.Messagerie
{

  public void envoyer (String auteur, String contenu) throws chat.MessageInterdit
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("envoyer", true);
                $out.write_string (auteur);
                $out.write_string (contenu);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:chat/MessageInterdit:1.0"))
                    throw chat.MessageInterditHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                envoyer (auteur, contenu        );
            } finally {
                _releaseReply ($in);
            }
  } // envoyer

  public void sAbonner (chat.Notifiable abonne)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("sAbonner", true);
                chat.NotifiableHelper.write ($out, abonne);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                sAbonner (abonne        );
            } finally {
                _releaseReply ($in);
            }
  } // sAbonner

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:chat/Messagerie:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "chat._MessagerieStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _MessagerieStub
