package chat;


/**
* chat/MessageriePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../app.idl
* mardi 22 septembre 2026 22 h 03 EAT
*/


// Servi par le serveur C++ : stocke en MySQL et notifie les abonnes
public abstract class MessageriePOA extends org.omg.PortableServer.Servant
 implements chat.MessagerieOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("envoyer", new java.lang.Integer (0));
    _methods.put ("sAbonner", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // chat/Messagerie/envoyer
       {
         String auteur = in.read_string ();
         String contenu = in.read_string ();
         this.envoyer (auteur, contenu);
         out = $rh.createReply();
         break;
       }

       case 1:  // chat/Messagerie/sAbonner
       {
         chat.Notifiable abonne = chat.NotifiableHelper.read (in);
         this.sAbonner (abonne);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:chat/Messagerie:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Messagerie _this() 
  {
    return MessagerieHelper.narrow(
    super._this_object());
  }

  public Messagerie _this(org.omg.CORBA.ORB orb) 
  {
    return MessagerieHelper.narrow(
    super._this_object(orb));
  }


} // class MessageriePOA
