package chat;


/**
* chat/MessagerieOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../app.idl
* mardi 22 septembre 2026 22 h 30 EAT
*/


// Servi par le serveur C++ : verifie, stocke en MySQL et notifie les abonnes
public interface MessagerieOperations 
{
  void envoyer (String auteur, String contenu) throws chat.MessageInterdit;
  void sAbonner (chat.Notifiable abonne);
} // interface MessagerieOperations
