package chat;


/**
* chat/Messagerie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../app.idl
* mardi 22 septembre 2026 22 h 03 EAT
*/


// Servi par le serveur C++ : stocke en MySQL et notifie les abonnes
public interface Messagerie extends MessagerieOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Messagerie
