package chat;


/**
* chat/MessagerieHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../app.idl
* mardi 22 septembre 2026 22 h 03 EAT
*/


// Servi par le serveur C++ : stocke en MySQL et notifie les abonnes
abstract public class MessagerieHelper
{
  private static String  _id = "IDL:chat/Messagerie:1.0";

  public static void insert (org.omg.CORBA.Any a, chat.Messagerie that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static chat.Messagerie extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (chat.MessagerieHelper.id (), "Messagerie");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static chat.Messagerie read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MessagerieStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, chat.Messagerie value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static chat.Messagerie narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof chat.Messagerie)
      return (chat.Messagerie)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      chat._MessagerieStub stub = new chat._MessagerieStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static chat.Messagerie unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof chat.Messagerie)
      return (chat.Messagerie)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      chat._MessagerieStub stub = new chat._MessagerieStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
