package chat;

/**
* chat/MessagerieHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../app.idl
* mardi 22 septembre 2026 22 h 30 EAT
*/


// Servi par le serveur C++ : verifie, stocke en MySQL et notifie les abonnes
public final class MessagerieHolder implements org.omg.CORBA.portable.Streamable
{
  public chat.Messagerie value = null;

  public MessagerieHolder ()
  {
  }

  public MessagerieHolder (chat.Messagerie initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chat.MessagerieHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chat.MessagerieHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chat.MessagerieHelper.type ();
  }

}
