package chat;


/**
* chat/MessageInterdit.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../app.idl
* mardi 22 septembre 2026 22 h 30 EAT
*/

public final class MessageInterdit extends org.omg.CORBA.UserException
{
  public String mot = null;

  public MessageInterdit ()
  {
    super(MessageInterditHelper.id());
  } // ctor

  public MessageInterdit (String _mot)
  {
    super(MessageInterditHelper.id());
    mot = _mot;
  } // ctor


  public MessageInterdit (String $reason, String _mot)
  {
    super(MessageInterditHelper.id() + "  " + $reason);
    mot = _mot;
  } // ctor

} // class MessageInterdit
