package chat;

/**
* chat/MessageInterditHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../app.idl
* mardi 22 septembre 2026 22 h 30 EAT
*/

public final class MessageInterditHolder implements org.omg.CORBA.portable.Streamable
{
  public chat.MessageInterdit value = null;

  public MessageInterditHolder ()
  {
  }

  public MessageInterditHolder (chat.MessageInterdit initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chat.MessageInterditHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chat.MessageInterditHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chat.MessageInterditHelper.type ();
  }

}
