package chat;

/**
* chat/ModerateurHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../app.idl
* mardi 22 septembre 2026 22 h 30 EAT
*/


// ou "" si le message est propre. C'est C++ qui l'appelle.
public final class ModerateurHolder implements org.omg.CORBA.portable.Streamable
{
  public chat.Moderateur value = null;

  public ModerateurHolder ()
  {
  }

  public ModerateurHolder (chat.Moderateur initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chat.ModerateurHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chat.ModerateurHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chat.ModerateurHelper.type ();
  }

}
