package chat;


/**
* chat/ModerateurPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../app.idl
* mardi 22 septembre 2026 22 h 30 EAT
*/


// ou "" si le message est propre. C'est C++ qui l'appelle.
public abstract class ModerateurPOA extends org.omg.PortableServer.Servant
 implements chat.ModerateurOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("chercherMotTabou", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // chat/Moderateur/chercherMotTabou
       {
         String contenu = in.read_string ();
         String $result = null;
         $result = this.chercherMotTabou (contenu);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:chat/Moderateur:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Moderateur _this() 
  {
    return ModerateurHelper.narrow(
    super._this_object());
  }

  public Moderateur _this(org.omg.CORBA.ORB orb) 
  {
    return ModerateurHelper.narrow(
    super._this_object(orb));
  }


} // class ModerateurPOA
