package chat;


/**
* chat/ModerateurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../app.idl
* mardi 22 septembre 2026 22 h 30 EAT
*/


// ou "" si le message est propre. C'est C++ qui l'appelle.
public interface ModerateurOperations 
{
  String chercherMotTabou (String contenu);
} // interface ModerateurOperations
