package chat;


/**
* chat/Notifiable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../app.idl
* mardi 22 septembre 2026 22 h 03 EAT
*/


// Servi par le CLIENT Java : c'est l'objet que le serveur C++ rappelle
public interface Notifiable extends NotifiableOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Notifiable
