package chat;


/**
* chat/NotifiablePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../app.idl
* mardi 22 septembre 2026 22 h 03 EAT
*/


// Servi par le CLIENT Java : c'est l'objet que le serveur C++ rappelle
public abstract class NotifiablePOA extends org.omg.PortableServer.Servant
 implements chat.NotifiableOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("nouveauMessage", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // chat/Notifiable/nouveauMessage
       {
         String auteur = in.read_string ();
         String contenu = in.read_string ();
         this.nouveauMessage (auteur, contenu);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:chat/Notifiable:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Notifiable _this() 
  {
    return NotifiableHelper.narrow(
    super._this_object());
  }

  public Notifiable _this(org.omg.CORBA.ORB orb) 
  {
    return NotifiableHelper.narrow(
    super._this_object(orb));
  }


} // class NotifiablePOA
