package chat;

/**
* chat/NotifiableHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../app.idl
* mardi 22 septembre 2026 22 h 03 EAT
*/


// Servi par le CLIENT Java : c'est l'objet que le serveur C++ rappelle
public final class NotifiableHolder implements org.omg.CORBA.portable.Streamable
{
  public chat.Notifiable value = null;

  public NotifiableHolder ()
  {
  }

  public NotifiableHolder (chat.Notifiable initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chat.NotifiableHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chat.NotifiableHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chat.NotifiableHelper.type ();
  }

}
