package chat;


/**
* chat/NotifiableOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../app.idl
* mardi 22 septembre 2026 22 h 30 EAT
*/


// Servi par le CLIENT Java : c'est l'objet que le serveur C++ rappelle
public interface NotifiableOperations 
{
  void nouveauMessage (String auteur, String contenu);
} // interface NotifiableOperations
