package boutique;


/**
* boutique/_StockStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../boutique.idl
* mercredi 23 septembre 2026 20 h 05 EAT
*/


// Servi par C++ : verifie et decremente le stock MySQL. C'est Java qui l'appelle.
public class _StockStub extends org.omg.CORBA.portable.ObjectImpl implements boutique.Stock
{

  public int acheter (String produit) throws boutique.StockInsuffisant
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("acheter", true);
                $out.write_string (produit);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:boutique/StockInsuffisant:1.0"))
                    throw boutique.StockInsuffisantHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return acheter (produit        );
            } finally {
                _releaseReply ($in);
            }
  } // acheter

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:boutique/Stock:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "boutique._StockStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _StockStub
