package boutique;


/**
* boutique/CommandeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../boutique.idl
* mercredi 23 septembre 2026 20 h 05 EAT
*/


// Servi par JAVA : lit data/commande.txt. C'est C++ qui l'appelle.
public interface CommandeOperations 
{
  int quantiteDemandee (String produit);
} // interface CommandeOperations
