package boutique;


/**
* boutique/CommandeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../boutique.idl
* mercredi 23 septembre 2026 20 h 05 EAT
*/


// Servi par JAVA : lit data/commande.txt. C'est C++ qui l'appelle.
abstract public class CommandeHelper
{
  private static String  _id = "IDL:boutique/Commande:1.0";

  public static void insert (org.omg.CORBA.Any a, boutique.Commande that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static boutique.Commande extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (boutique.CommandeHelper.id (), "Commande");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static boutique.Commande read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CommandeStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, boutique.Commande value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static boutique.Commande narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof boutique.Commande)
      return (boutique.Commande)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      boutique._CommandeStub stub = new boutique._CommandeStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static boutique.Commande unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof boutique.Commande)
      return (boutique.Commande)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      boutique._CommandeStub stub = new boutique._CommandeStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
