package boutique;

/**
* boutique/CommandeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../boutique.idl
* mercredi 23 septembre 2026 20 h 05 EAT
*/


// Servi par JAVA : lit data/commande.txt. C'est C++ qui l'appelle.
public final class CommandeHolder implements org.omg.CORBA.portable.Streamable
{
  public boutique.Commande value = null;

  public CommandeHolder ()
  {
  }

  public CommandeHolder (boutique.Commande initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = boutique.CommandeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    boutique.CommandeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return boutique.CommandeHelper.type ();
  }

}
