package boutique;

/**
* boutique/StockInsuffisantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../boutique.idl
* mercredi 23 septembre 2026 20 h 05 EAT
*/

public final class StockInsuffisantHolder implements org.omg.CORBA.portable.Streamable
{
  public boutique.StockInsuffisant value = null;

  public StockInsuffisantHolder ()
  {
  }

  public StockInsuffisantHolder (boutique.StockInsuffisant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = boutique.StockInsuffisantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    boutique.StockInsuffisantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return boutique.StockInsuffisantHelper.type ();
  }

}
