package boutique;

/**
* boutique/StockHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../boutique.idl
* mercredi 23 septembre 2026 20 h 05 EAT
*/


// Servi par C++ : verifie et decremente le stock MySQL. C'est Java qui l'appelle.
public final class StockHolder implements org.omg.CORBA.portable.Streamable
{
  public boutique.Stock value = null;

  public StockHolder ()
  {
  }

  public StockHolder (boutique.Stock initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = boutique.StockHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    boutique.StockHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return boutique.StockHelper.type ();
  }

}
