package boutique;


/**
* boutique/StockPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../boutique.idl
* mercredi 23 septembre 2026 20 h 05 EAT
*/


// Servi par C++ : verifie et decremente le stock MySQL. C'est Java qui l'appelle.
public abstract class StockPOA extends org.omg.PortableServer.Servant
 implements boutique.StockOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("acheter", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // boutique/Stock/acheter
       {
         try {
           String produit = in.read_string ();
           int $result = (int)0;
           $result = this.acheter (produit);
           out = $rh.createReply();
           out.write_long ($result);
         } catch (boutique.StockInsuffisant $ex) {
           out = $rh.createExceptionReply ();
           boutique.StockInsuffisantHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:boutique/Stock:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Stock _this() 
  {
    return StockHelper.narrow(
    super._this_object());
  }

  public Stock _this(org.omg.CORBA.ORB orb) 
  {
    return StockHelper.narrow(
    super._this_object(orb));
  }


} // class StockPOA
