package boutique;


/**
* boutique/StockInsuffisantHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../boutique.idl
* mercredi 23 septembre 2026 20 h 05 EAT
*/

abstract public class StockInsuffisantHelper
{
  private static String  _id = "IDL:boutique/StockInsuffisant:1.0";

  public static void insert (org.omg.CORBA.Any a, boutique.StockInsuffisant that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static boutique.StockInsuffisant extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "disponible",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (boutique.StockInsuffisantHelper.id (), "StockInsuffisant", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static boutique.StockInsuffisant read (org.omg.CORBA.portable.InputStream istream)
  {
    boutique.StockInsuffisant value = new boutique.StockInsuffisant ();
    // read and discard the repository ID
    istream.read_string ();
    value.disponible = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, boutique.StockInsuffisant value)
  {
    // write the repository ID
    ostream.write_string (id ());
    ostream.write_long (value.disponible);
  }

}
