package boutique;


/**
* boutique/StockInsuffisant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../boutique.idl
* mercredi 23 septembre 2026 20 h 05 EAT
*/

public final class StockInsuffisant extends org.omg.CORBA.UserException
{
  public int disponible = (int)0;

  public StockInsuffisant ()
  {
    super(StockInsuffisantHelper.id());
  } // ctor

  public StockInsuffisant (int _disponible)
  {
    super(StockInsuffisantHelper.id());
    disponible = _disponible;
  } // ctor


  public StockInsuffisant (String $reason, int _disponible)
  {
    super(StockInsuffisantHelper.id() + "  " + $reason);
    disponible = _disponible;
  } // ctor

} // class StockInsuffisant
