package boutique;


/**
* boutique/StockOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../boutique.idl
* mercredi 23 septembre 2026 20 h 05 EAT
*/


// Servi par C++ : verifie et decremente le stock MySQL. C'est Java qui l'appelle.
public interface StockOperations 
{
  int acheter (String produit) throws boutique.StockInsuffisant;
} // interface StockOperations
