// This file is generated by omniidl (C++ backend)- omniORB_4_3. Do not edit.
#ifndef __app_hh__
#define __app_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_app
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_app
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_app
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE app

_CORBA_MODULE_BEG

#ifndef __app_mFileService__
#define __app_mFileService__
  class FileService;
  class _objref_FileService;
  class _impl_FileService;
  
  typedef _objref_FileService* FileService_ptr;
  typedef FileService_ptr FileServiceRef;

  class FileService_Helper {
  public:
    typedef FileService_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_FileService, FileService_Helper> FileService_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_FileService,FileService_Helper > FileService_out;

#endif

  // interface FileService
  class FileService {
  public:
    // Declarations for this interface type.
    typedef FileService_ptr _ptr_type;
    typedef FileService_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_FileService :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    char* readMessage();
    void writeMessage(const char* msg);

    // Constructors
    inline _objref_FileService()  { _PR_setobj(0); }  // nil
    _objref_FileService(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_FileService();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_FileService(const _objref_FileService&);
    _objref_FileService& operator = (const _objref_FileService&);
    // not implemented

    friend class FileService;
  };

  class _pof_FileService : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_FileService() : _OMNI_NS(proxyObjectFactory)(FileService::_PD_repoId) {}
    virtual ~_pof_FileService();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_FileService :
    public virtual omniServant
  {
  public:
    virtual ~_impl_FileService();

    virtual char* readMessage() = 0;
    virtual void writeMessage(const char* msg) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


#ifndef __app_mDataService__
#define __app_mDataService__
  class DataService;
  class _objref_DataService;
  class _impl_DataService;
  
  typedef _objref_DataService* DataService_ptr;
  typedef DataService_ptr DataServiceRef;

  class DataService_Helper {
  public:
    typedef DataService_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_DataService, DataService_Helper> DataService_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_DataService,DataService_Helper > DataService_out;

#endif

  // interface DataService
  class DataService {
  public:
    // Declarations for this interface type.
    typedef DataService_ptr _ptr_type;
    typedef DataService_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_DataService :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    char* getData();
    void saveData(const char* value);

    // Constructors
    inline _objref_DataService()  { _PR_setobj(0); }  // nil
    _objref_DataService(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_DataService();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_DataService(const _objref_DataService&);
    _objref_DataService& operator = (const _objref_DataService&);
    // not implemented

    friend class DataService;
  };

  class _pof_DataService : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_DataService() : _OMNI_NS(proxyObjectFactory)(DataService::_PD_repoId) {}
    virtual ~_pof_DataService();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_DataService :
    public virtual omniServant
  {
  public:
    virtual ~_impl_DataService();

    virtual char* getData() = 0;
    virtual void saveData(const char* value) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_app
_CORBA_MODULE_BEG

  class FileService :
    public virtual app::_impl_FileService,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~FileService();

    inline ::app::FileService_ptr _this() {
      return (::app::FileService_ptr) _do_this(::app::FileService::_PD_repoId);
    }
  };

  class DataService :
    public virtual app::_impl_DataService,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~DataService();

    inline ::app::DataService_ptr _this() {
      return (::app::DataService_ptr) _do_this(::app::DataService::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_app
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
app::FileService::_marshalObjRef(::app::FileService_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}

inline void
app::DataService::_marshalObjRef(::app::DataService_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_app
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_app
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_app
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_app
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_app
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_app
#endif

#endif  // __app_hh__

