// This file is generated by omniidl (C++ backend) - omniORB_4_3. Do not edit.

#include "app.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

OMNI_MAYBE_UNUSED static const char* _0RL_library_version = omniORB_4_3;



app::FileService_ptr app::FileService_Helper::_nil() {
  return ::app::FileService::_nil();
}

::CORBA::Boolean app::FileService_Helper::is_nil(::app::FileService_ptr p) {
  return ::CORBA::is_nil(p);

}

void app::FileService_Helper::release(::app::FileService_ptr p) {
  ::CORBA::release(p);
}

void app::FileService_Helper::marshalObjRef(::app::FileService_ptr obj, cdrStream& s) {
  ::app::FileService::_marshalObjRef(obj, s);
}

app::FileService_ptr app::FileService_Helper::unmarshalObjRef(cdrStream& s) {
  return ::app::FileService::_unmarshalObjRef(s);
}

void app::FileService_Helper::duplicate(::app::FileService_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

app::FileService_ptr
app::FileService::_duplicate(::app::FileService_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

app::FileService_ptr
app::FileService::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


app::FileService_ptr
app::FileService::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

app::FileService_ptr
app::FileService::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_FileService _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_FileService* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_FileService;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* app::FileService::_PD_repoId = "IDL:app/FileService:1.0";


app::_objref_FileService::~_objref_FileService() {
  
}


app::_objref_FileService::_objref_FileService(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::app::FileService::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
app::_objref_FileService::_ptrToObjRef(const char* id)
{
  if (id == ::app::FileService::_PD_repoId)
    return (::app::FileService_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::app::FileService::_PD_repoId))
    return (::app::FileService_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for app::FileService::readMessage

// Proxy call descriptor class. Mangled signature:
//  _cstring
class _0RL_cd_d290094803393e4b_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_d290094803393e4b_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var result;
};

void _0RL_cd_d290094803393e4b_00000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalString(result,0);

}

void _0RL_cd_d290094803393e4b_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalString(0);

}

const char* const _0RL_cd_d290094803393e4b_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_d290094803393e4b_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_d290094803393e4b_00000000* tcd = (_0RL_cd_d290094803393e4b_00000000*)cd;
  app::_impl_FileService* impl = (app::_impl_FileService*) svnt->_ptrToInterface(app::FileService::_PD_repoId);
  tcd->result = impl->readMessage();


}

char* app::_objref_FileService::readMessage()
{
  _0RL_cd_d290094803393e4b_00000000 _call_desc(_0RL_lcfn_d290094803393e4b_10000000, "readMessage", 12);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for app::FileService::writeMessage

// Proxy call descriptor class. Mangled signature:
//  void_i_cstring
class _0RL_cd_d290094803393e4b_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_d290094803393e4b_20000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
};

void _0RL_cd_d290094803393e4b_20000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);

}

void _0RL_cd_d290094803393e4b_20000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();

}

const char* const _0RL_cd_d290094803393e4b_20000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_d290094803393e4b_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_d290094803393e4b_20000000* tcd = (_0RL_cd_d290094803393e4b_20000000*)cd;
  app::_impl_FileService* impl = (app::_impl_FileService*) svnt->_ptrToInterface(app::FileService::_PD_repoId);
  impl->writeMessage(tcd->arg_0);


}

void app::_objref_FileService::writeMessage(const char* msg)
{
  _0RL_cd_d290094803393e4b_20000000 _call_desc(_0RL_lcfn_d290094803393e4b_30000000, "writeMessage", 13);
  _call_desc.arg_0 = msg;

  _invoke(_call_desc);



}

app::_pof_FileService::~_pof_FileService() {}


omniObjRef*
app::_pof_FileService::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::app::_objref_FileService(ior, id);
}


::CORBA::Boolean
app::_pof_FileService::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::app::FileService::_PD_repoId))
    return 1;
  
  return 0;
}

const app::_pof_FileService _the_pof_app_mFileService;

app::_impl_FileService::~_impl_FileService() {}


::CORBA::Boolean
app::_impl_FileService::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "readMessage")) {

    _0RL_cd_d290094803393e4b_00000000 _call_desc(_0RL_lcfn_d290094803393e4b_10000000, "readMessage", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "writeMessage")) {

    _0RL_cd_d290094803393e4b_20000000 _call_desc(_0RL_lcfn_d290094803393e4b_30000000, "writeMessage", 13, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
app::_impl_FileService::_ptrToInterface(const char* id)
{
  if (id == ::app::FileService::_PD_repoId)
    return (::app::_impl_FileService*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::app::FileService::_PD_repoId))
    return (::app::_impl_FileService*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
app::_impl_FileService::_mostDerivedRepoId()
{
  return ::app::FileService::_PD_repoId;
}

app::DataService_ptr app::DataService_Helper::_nil() {
  return ::app::DataService::_nil();
}

::CORBA::Boolean app::DataService_Helper::is_nil(::app::DataService_ptr p) {
  return ::CORBA::is_nil(p);

}

void app::DataService_Helper::release(::app::DataService_ptr p) {
  ::CORBA::release(p);
}

void app::DataService_Helper::marshalObjRef(::app::DataService_ptr obj, cdrStream& s) {
  ::app::DataService::_marshalObjRef(obj, s);
}

app::DataService_ptr app::DataService_Helper::unmarshalObjRef(cdrStream& s) {
  return ::app::DataService::_unmarshalObjRef(s);
}

void app::DataService_Helper::duplicate(::app::DataService_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

app::DataService_ptr
app::DataService::_duplicate(::app::DataService_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

app::DataService_ptr
app::DataService::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


app::DataService_ptr
app::DataService::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

app::DataService_ptr
app::DataService::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_DataService _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_DataService* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_DataService;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* app::DataService::_PD_repoId = "IDL:app/DataService:1.0";


app::_objref_DataService::~_objref_DataService() {
  
}


app::_objref_DataService::_objref_DataService(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::app::DataService::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
app::_objref_DataService::_ptrToObjRef(const char* id)
{
  if (id == ::app::DataService::_PD_repoId)
    return (::app::DataService_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::app::DataService::_PD_repoId))
    return (::app::DataService_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for app::DataService::getData

// Local call call-back function.
static void
_0RL_lcfn_d290094803393e4b_40000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_d290094803393e4b_00000000* tcd = (_0RL_cd_d290094803393e4b_00000000*)cd;
  app::_impl_DataService* impl = (app::_impl_DataService*) svnt->_ptrToInterface(app::DataService::_PD_repoId);
  tcd->result = impl->getData();


}

char* app::_objref_DataService::getData()
{
  _0RL_cd_d290094803393e4b_00000000 _call_desc(_0RL_lcfn_d290094803393e4b_40000000, "getData", 8);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for app::DataService::saveData

// Local call call-back function.
static void
_0RL_lcfn_d290094803393e4b_50000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_d290094803393e4b_20000000* tcd = (_0RL_cd_d290094803393e4b_20000000*)cd;
  app::_impl_DataService* impl = (app::_impl_DataService*) svnt->_ptrToInterface(app::DataService::_PD_repoId);
  impl->saveData(tcd->arg_0);


}

void app::_objref_DataService::saveData(const char* value)
{
  _0RL_cd_d290094803393e4b_20000000 _call_desc(_0RL_lcfn_d290094803393e4b_50000000, "saveData", 9);
  _call_desc.arg_0 = value;

  _invoke(_call_desc);



}

app::_pof_DataService::~_pof_DataService() {}


omniObjRef*
app::_pof_DataService::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::app::_objref_DataService(ior, id);
}


::CORBA::Boolean
app::_pof_DataService::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::app::DataService::_PD_repoId))
    return 1;
  
  return 0;
}

const app::_pof_DataService _the_pof_app_mDataService;

app::_impl_DataService::~_impl_DataService() {}


::CORBA::Boolean
app::_impl_DataService::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "getData")) {

    _0RL_cd_d290094803393e4b_00000000 _call_desc(_0RL_lcfn_d290094803393e4b_40000000, "getData", 8, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "saveData")) {

    _0RL_cd_d290094803393e4b_20000000 _call_desc(_0RL_lcfn_d290094803393e4b_50000000, "saveData", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
app::_impl_DataService::_ptrToInterface(const char* id)
{
  if (id == ::app::DataService::_PD_repoId)
    return (::app::_impl_DataService*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::app::DataService::_PD_repoId))
    return (::app::_impl_DataService*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
app::_impl_DataService::_mostDerivedRepoId()
{
  return ::app::DataService::_PD_repoId;
}

POA_app::FileService::~FileService() {}

POA_app::DataService::~DataService() {}

