package helloapp;


/**
* helloapp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* mardi 22 septembre 2026 14 h 57 EAT
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
