package app;

/**
* app/DataServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../app.idl
* mardi 22 septembre 2026 15 h 48 EAT
*/

public final class DataServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public app.DataService value = null;

  public DataServiceHolder ()
  {
  }

  public DataServiceHolder (app.DataService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = app.DataServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    app.DataServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return app.DataServiceHelper.type ();
  }

}
