package app;


/**
* app/DataServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../app.idl
* mardi 22 septembre 2026 15 h 48 EAT
*/

public interface DataServiceOperations 
{
  String getData ();
  void saveData (String value);
} // interface DataServiceOperations
