package app;


/**
* app/DataServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../app.idl
* mardi 22 septembre 2026 15 h 48 EAT
*/

abstract public class DataServiceHelper
{
  private static String  _id = "IDL:app/DataService:1.0";

  public static void insert (org.omg.CORBA.Any a, app.DataService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static app.DataService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (app.DataServiceHelper.id (), "DataService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static app.DataService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DataServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, app.DataService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static app.DataService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof app.DataService)
      return (app.DataService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      app._DataServiceStub stub = new app._DataServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static app.DataService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof app.DataService)
      return (app.DataService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      app._DataServiceStub stub = new app._DataServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
