package app;


/**
* app/FileServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../app.idl
* mardi 22 septembre 2026 15 h 48 EAT
*/

public abstract class FileServicePOA extends org.omg.PortableServer.Servant
 implements app.FileServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("readMessage", new java.lang.Integer (0));
    _methods.put ("writeMessage", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // app/FileService/readMessage
       {
         String $result = null;
         $result = this.readMessage ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // app/FileService/writeMessage
       {
         String msg = in.read_string ();
         this.writeMessage (msg);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:app/FileService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FileService _this() 
  {
    return FileServiceHelper.narrow(
    super._this_object());
  }

  public FileService _this(org.omg.CORBA.ORB orb) 
  {
    return FileServiceHelper.narrow(
    super._this_object(orb));
  }


} // class FileServicePOA
