package app;

/**
* app/FileServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../app.idl
* mardi 22 septembre 2026 15 h 48 EAT
*/

public final class FileServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public app.FileService value = null;

  public FileServiceHolder ()
  {
  }

  public FileServiceHolder (app.FileService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = app.FileServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    app.FileServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return app.FileServiceHelper.type ();
  }

}
