package ecole;


/**
* ecole/_GestionEtudiantsStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/

public class _GestionEtudiantsStub extends org.omg.CORBA.portable.ObjectImpl implements ecole.GestionEtudiants
{


  // --- CRUD etudiants ---
  public int ajouterEtudiant (String nom, String prenom, String classe)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ajouterEtudiant", true);
                $out.write_string (nom);
                $out.write_string (prenom);
                $out.write_string (classe);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return ajouterEtudiant (nom, prenom, classe        );
            } finally {
                _releaseReply ($in);
            }
  } // ajouterEtudiant

  public boolean modifierEtudiant (int id, String nom, String prenom, String classe)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("modifierEtudiant", true);
                $out.write_long (id);
                $out.write_string (nom);
                $out.write_string (prenom);
                $out.write_string (classe);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return modifierEtudiant (id, nom, prenom, classe        );
            } finally {
                _releaseReply ($in);
            }
  } // modifierEtudiant

  public boolean supprimerEtudiant (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("supprimerEtudiant", true);
                $out.write_long (id);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return supprimerEtudiant (id        );
            } finally {
                _releaseReply ($in);
            }
  } // supprimerEtudiant

  public ecole.Etudiant[] listerEtudiants ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listerEtudiants", true);
                $in = _invoke ($out);
                ecole.Etudiant $result[] = ecole.ListeEtudiantsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listerEtudiants (        );
            } finally {
                _releaseReply ($in);
            }
  } // listerEtudiants

  public ecole.Etudiant rechercherEtudiant (int id) throws ecole.EtudiantIntrouvable
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("rechercherEtudiant", true);
                $out.write_long (id);
                $in = _invoke ($out);
                ecole.Etudiant $result = ecole.EtudiantHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:ecole/EtudiantIntrouvable:1.0"))
                    throw ecole.EtudiantIntrouvableHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return rechercherEtudiant (id        );
            } finally {
                _releaseReply ($in);
            }
  } // rechercherEtudiant


  // --- Notes ---
  public void ajouterNote (int etudiantId, String matiere, double note)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ajouterNote", true);
                $out.write_long (etudiantId);
                $out.write_string (matiere);
                $out.write_double (note);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                ajouterNote (etudiantId, matiere, note        );
            } finally {
                _releaseReply ($in);
            }
  } // ajouterNote


  // --- Calcul ---
  public double calculerMoyenne (int etudiantId) throws ecole.EtudiantIntrouvable
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("calculerMoyenne", true);
                $out.write_long (etudiantId);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:ecole/EtudiantIntrouvable:1.0"))
                    throw ecole.EtudiantIntrouvableHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return calculerMoyenne (etudiantId        );
            } finally {
                _releaseReply ($in);
            }
  } // calculerMoyenne


  // --- Bidirectionnel : C++ appelle Java pour obtenir la mention ---
  public void enregistrerMentionService (ecole.MentionService svc)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("enregistrerMentionService", true);
                ecole.MentionServiceHelper.write ($out, svc);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                enregistrerMentionService (svc        );
            } finally {
                _releaseReply ($in);
            }
  } // enregistrerMentionService

  public String obtenirMention (int etudiantId) throws ecole.EtudiantIntrouvable
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("obtenirMention", true);
                $out.write_long (etudiantId);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:ecole/EtudiantIntrouvable:1.0"))
                    throw ecole.EtudiantIntrouvableHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return obtenirMention (etudiantId        );
            } finally {
                _releaseReply ($in);
            }
  } // obtenirMention


  // --- Bidirectionnel : C++ recherche l'etudiant, puis demande a Java d'ecrire sa fiche ---
  public void enregistrerFicheService (ecole.FicheService svc)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("enregistrerFicheService", true);
                ecole.FicheServiceHelper.write ($out, svc);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                enregistrerFicheService (svc        );
            } finally {
                _releaseReply ($in);
            }
  } // enregistrerFicheService

  public void genererFiche (int etudiantId) throws ecole.EtudiantIntrouvable
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("genererFiche", true);
                $out.write_long (etudiantId);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:ecole/EtudiantIntrouvable:1.0"))
                    throw ecole.EtudiantIntrouvableHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                genererFiche (etudiantId        );
            } finally {
                _releaseReply ($in);
            }
  } // genererFiche


  // --- Bidirectionnel : C++ demande a Java si la classe est valide avant de modifier ---
  public void enregistrerValidationService (ecole.ValidationService svc)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("enregistrerValidationService", true);
                ecole.ValidationServiceHelper.write ($out, svc);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                enregistrerValidationService (svc        );
            } finally {
                _releaseReply ($in);
            }
  } // enregistrerValidationService

  public boolean changerClasse (int etudiantId, String nouvelleClasse) throws ecole.EtudiantIntrouvable
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("changerClasse", true);
                $out.write_long (etudiantId);
                $out.write_string (nouvelleClasse);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:ecole/EtudiantIntrouvable:1.0"))
                    throw ecole.EtudiantIntrouvableHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return changerClasse (etudiantId, nouvelleClasse        );
            } finally {
                _releaseReply ($in);
            }
  } // changerClasse


  // --- Bidirectionnel : C++ demande a Java la penalite (lue dans un fichier), puis l'applique ---
  public void enregistrerPenaliteService (ecole.PenaliteService svc)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("enregistrerPenaliteService", true);
                ecole.PenaliteServiceHelper.write ($out, svc);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                enregistrerPenaliteService (svc        );
            } finally {
                _releaseReply ($in);
            }
  } // enregistrerPenaliteService

  public boolean appliquerPenalite (int etudiantId, String matiere) throws ecole.EtudiantIntrouvable
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("appliquerPenalite", true);
                $out.write_long (etudiantId);
                $out.write_string (matiere);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:ecole/EtudiantIntrouvable:1.0"))
                    throw ecole.EtudiantIntrouvableHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return appliquerPenalite (etudiantId, matiere        );
            } finally {
                _releaseReply ($in);
            }
  } // appliquerPenalite

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ecole/GestionEtudiants:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "ecole._GestionEtudiantsStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GestionEtudiantsStub
