package ecole;

/**
* ecole/EtudiantIntrouvableHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/

public final class EtudiantIntrouvableHolder implements org.omg.CORBA.portable.Streamable
{
  public ecole.EtudiantIntrouvable value = null;

  public EtudiantIntrouvableHolder ()
  {
  }

  public EtudiantIntrouvableHolder (ecole.EtudiantIntrouvable initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ecole.EtudiantIntrouvableHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ecole.EtudiantIntrouvableHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ecole.EtudiantIntrouvableHelper.type ();
  }

}
