package ecole;


/**
* ecole/EtudiantIntrouvable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/

public final class EtudiantIntrouvable extends org.omg.CORBA.UserException
{
  public int id = (int)0;

  public EtudiantIntrouvable ()
  {
    super(EtudiantIntrouvableHelper.id());
  } // ctor

  public EtudiantIntrouvable (int _id)
  {
    super(EtudiantIntrouvableHelper.id());
    id = _id;
  } // ctor


  public EtudiantIntrouvable (String $reason, int _id)
  {
    super(EtudiantIntrouvableHelper.id() + "  " + $reason);
    id = _id;
  } // ctor

} // class EtudiantIntrouvable
