package ecole;

/**
* ecole/EtudiantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/

public final class EtudiantHolder implements org.omg.CORBA.portable.Streamable
{
  public ecole.Etudiant value = null;

  public EtudiantHolder ()
  {
  }

  public EtudiantHolder (ecole.Etudiant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ecole.EtudiantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ecole.EtudiantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ecole.EtudiantHelper.type ();
  }

}
