package ecole;


/**
* ecole/Etudiant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/

public final class Etudiant implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String nom = null;
  public String prenom = null;
  public String classe = null;

  public Etudiant ()
  {
  } // ctor

  public Etudiant (int _id, String _nom, String _prenom, String _classe)
  {
    id = _id;
    nom = _nom;
    prenom = _prenom;
    classe = _classe;
  } // ctor

} // class Etudiant
