package ecole;


/**
* ecole/FicheServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/


// Servi par JAVA : ecrit la fiche complete d'un etudiant dans un fichier.
public abstract class FicheServicePOA extends org.omg.PortableServer.Servant
 implements ecole.FicheServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("ecrireFiche", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ecole/FicheService/ecrireFiche
       {
         ecole.Etudiant e = ecole.EtudiantHelper.read (in);
         double moyenne = in.read_double ();
         String mention = in.read_string ();
         this.ecrireFiche (e, moyenne, mention);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ecole/FicheService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FicheService _this() 
  {
    return FicheServiceHelper.narrow(
    super._this_object());
  }

  public FicheService _this(org.omg.CORBA.ORB orb) 
  {
    return FicheServiceHelper.narrow(
    super._this_object(orb));
  }


} // class FicheServicePOA
