package ecole;


/**
* ecole/FicheService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/


// Servi par JAVA : ecrit la fiche complete d'un etudiant dans un fichier.
public interface FicheService extends FicheServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FicheService
