package ecole;

/**
* ecole/FicheServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/


// Servi par JAVA : ecrit la fiche complete d'un etudiant dans un fichier.
public final class FicheServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public ecole.FicheService value = null;

  public FicheServiceHolder ()
  {
  }

  public FicheServiceHolder (ecole.FicheService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ecole.FicheServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ecole.FicheServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ecole.FicheServiceHelper.type ();
  }

}
