package ecole;


/**
* ecole/FicheServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/


// Servi par JAVA : ecrit la fiche complete d'un etudiant dans un fichier.
public interface FicheServiceOperations 
{
  void ecrireFiche (ecole.Etudiant e, double moyenne, String mention);
} // interface FicheServiceOperations
