package ecole;

/**
* ecole/GestionEtudiantsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/

public final class GestionEtudiantsHolder implements org.omg.CORBA.portable.Streamable
{
  public ecole.GestionEtudiants value = null;

  public GestionEtudiantsHolder ()
  {
  }

  public GestionEtudiantsHolder (ecole.GestionEtudiants initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ecole.GestionEtudiantsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ecole.GestionEtudiantsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ecole.GestionEtudiantsHelper.type ();
  }

}
