package ecole;


/**
* ecole/GestionEtudiantsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/

abstract public class GestionEtudiantsHelper
{
  private static String  _id = "IDL:ecole/GestionEtudiants:1.0";

  public static void insert (org.omg.CORBA.Any a, ecole.GestionEtudiants that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ecole.GestionEtudiants extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ecole.GestionEtudiantsHelper.id (), "GestionEtudiants");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ecole.GestionEtudiants read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GestionEtudiantsStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ecole.GestionEtudiants value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ecole.GestionEtudiants narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ecole.GestionEtudiants)
      return (ecole.GestionEtudiants)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ecole._GestionEtudiantsStub stub = new ecole._GestionEtudiantsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ecole.GestionEtudiants unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ecole.GestionEtudiants)
      return (ecole.GestionEtudiants)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ecole._GestionEtudiantsStub stub = new ecole._GestionEtudiantsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
