package ecole;


/**
* ecole/GestionEtudiantsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/

public abstract class GestionEtudiantsPOA extends org.omg.PortableServer.Servant
 implements ecole.GestionEtudiantsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("ajouterEtudiant", new java.lang.Integer (0));
    _methods.put ("modifierEtudiant", new java.lang.Integer (1));
    _methods.put ("supprimerEtudiant", new java.lang.Integer (2));
    _methods.put ("listerEtudiants", new java.lang.Integer (3));
    _methods.put ("rechercherEtudiant", new java.lang.Integer (4));
    _methods.put ("ajouterNote", new java.lang.Integer (5));
    _methods.put ("calculerMoyenne", new java.lang.Integer (6));
    _methods.put ("enregistrerMentionService", new java.lang.Integer (7));
    _methods.put ("obtenirMention", new java.lang.Integer (8));
    _methods.put ("enregistrerFicheService", new java.lang.Integer (9));
    _methods.put ("genererFiche", new java.lang.Integer (10));
    _methods.put ("enregistrerValidationService", new java.lang.Integer (11));
    _methods.put ("changerClasse", new java.lang.Integer (12));
    _methods.put ("enregistrerPenaliteService", new java.lang.Integer (13));
    _methods.put ("appliquerPenalite", new java.lang.Integer (14));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // --- CRUD etudiants ---
       case 0:  // ecole/GestionEtudiants/ajouterEtudiant
       {
         String nom = in.read_string ();
         String prenom = in.read_string ();
         String classe = in.read_string ();
         int $result = (int)0;
         $result = this.ajouterEtudiant (nom, prenom, classe);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // ecole/GestionEtudiants/modifierEtudiant
       {
         int id = in.read_long ();
         String nom = in.read_string ();
         String prenom = in.read_string ();
         String classe = in.read_string ();
         boolean $result = false;
         $result = this.modifierEtudiant (id, nom, prenom, classe);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // ecole/GestionEtudiants/supprimerEtudiant
       {
         int id = in.read_long ();
         boolean $result = false;
         $result = this.supprimerEtudiant (id);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // ecole/GestionEtudiants/listerEtudiants
       {
         ecole.Etudiant $result[] = null;
         $result = this.listerEtudiants ();
         out = $rh.createReply();
         ecole.ListeEtudiantsHelper.write (out, $result);
         break;
       }

       case 4:  // ecole/GestionEtudiants/rechercherEtudiant
       {
         try {
           int id = in.read_long ();
           ecole.Etudiant $result = null;
           $result = this.rechercherEtudiant (id);
           out = $rh.createReply();
           ecole.EtudiantHelper.write (out, $result);
         } catch (ecole.EtudiantIntrouvable $ex) {
           out = $rh.createExceptionReply ();
           ecole.EtudiantIntrouvableHelper.write (out, $ex);
         }
         break;
       }


  // --- Notes ---
       case 5:  // ecole/GestionEtudiants/ajouterNote
       {
         int etudiantId = in.read_long ();
         String matiere = in.read_string ();
         double note = in.read_double ();
         this.ajouterNote (etudiantId, matiere, note);
         out = $rh.createReply();
         break;
       }


  // --- Calcul ---
       case 6:  // ecole/GestionEtudiants/calculerMoyenne
       {
         try {
           int etudiantId = in.read_long ();
           double $result = (double)0;
           $result = this.calculerMoyenne (etudiantId);
           out = $rh.createReply();
           out.write_double ($result);
         } catch (ecole.EtudiantIntrouvable $ex) {
           out = $rh.createExceptionReply ();
           ecole.EtudiantIntrouvableHelper.write (out, $ex);
         }
         break;
       }


  // --- Bidirectionnel : C++ appelle Java pour obtenir la mention ---
       case 7:  // ecole/GestionEtudiants/enregistrerMentionService
       {
         ecole.MentionService svc = ecole.MentionServiceHelper.read (in);
         this.enregistrerMentionService (svc);
         out = $rh.createReply();
         break;
       }

       case 8:  // ecole/GestionEtudiants/obtenirMention
       {
         try {
           int etudiantId = in.read_long ();
           String $result = null;
           $result = this.obtenirMention (etudiantId);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (ecole.EtudiantIntrouvable $ex) {
           out = $rh.createExceptionReply ();
           ecole.EtudiantIntrouvableHelper.write (out, $ex);
         }
         break;
       }


  // --- Bidirectionnel : C++ recherche l'etudiant, puis demande a Java d'ecrire sa fiche ---
       case 9:  // ecole/GestionEtudiants/enregistrerFicheService
       {
         ecole.FicheService svc = ecole.FicheServiceHelper.read (in);
         this.enregistrerFicheService (svc);
         out = $rh.createReply();
         break;
       }

       case 10:  // ecole/GestionEtudiants/genererFiche
       {
         try {
           int etudiantId = in.read_long ();
           this.genererFiche (etudiantId);
           out = $rh.createReply();
         } catch (ecole.EtudiantIntrouvable $ex) {
           out = $rh.createExceptionReply ();
           ecole.EtudiantIntrouvableHelper.write (out, $ex);
         }
         break;
       }


  // --- Bidirectionnel : C++ demande a Java si la classe est valide avant de modifier ---
       case 11:  // ecole/GestionEtudiants/enregistrerValidationService
       {
         ecole.ValidationService svc = ecole.ValidationServiceHelper.read (in);
         this.enregistrerValidationService (svc);
         out = $rh.createReply();
         break;
       }

       case 12:  // ecole/GestionEtudiants/changerClasse
       {
         try {
           int etudiantId = in.read_long ();
           String nouvelleClasse = in.read_string ();
           boolean $result = false;
           $result = this.changerClasse (etudiantId, nouvelleClasse);
           out = $rh.createReply();
           out.write_boolean ($result);
         } catch (ecole.EtudiantIntrouvable $ex) {
           out = $rh.createExceptionReply ();
           ecole.EtudiantIntrouvableHelper.write (out, $ex);
         }
         break;
       }


  // --- Bidirectionnel : C++ demande a Java la penalite (lue dans un fichier), puis l'applique ---
       case 13:  // ecole/GestionEtudiants/enregistrerPenaliteService
       {
         ecole.PenaliteService svc = ecole.PenaliteServiceHelper.read (in);
         this.enregistrerPenaliteService (svc);
         out = $rh.createReply();
         break;
       }

       case 14:  // ecole/GestionEtudiants/appliquerPenalite
       {
         try {
           int etudiantId = in.read_long ();
           String matiere = in.read_string ();
           boolean $result = false;
           $result = this.appliquerPenalite (etudiantId, matiere);
           out = $rh.createReply();
           out.write_boolean ($result);
         } catch (ecole.EtudiantIntrouvable $ex) {
           out = $rh.createExceptionReply ();
           ecole.EtudiantIntrouvableHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ecole/GestionEtudiants:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GestionEtudiants _this() 
  {
    return GestionEtudiantsHelper.narrow(
    super._this_object());
  }

  public GestionEtudiants _this(org.omg.CORBA.ORB orb) 
  {
    return GestionEtudiantsHelper.narrow(
    super._this_object(orb));
  }


} // class GestionEtudiantsPOA
