package ecole;


/**
* ecole/GestionEtudiantsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/

public interface GestionEtudiantsOperations 
{

  // --- CRUD etudiants ---
  int ajouterEtudiant (String nom, String prenom, String classe);
  boolean modifierEtudiant (int id, String nom, String prenom, String classe);
  boolean supprimerEtudiant (int id);
  ecole.Etudiant[] listerEtudiants ();
  ecole.Etudiant rechercherEtudiant (int id) throws ecole.EtudiantIntrouvable;

  // --- Notes ---
  void ajouterNote (int etudiantId, String matiere, double note);

  // --- Calcul ---
  double calculerMoyenne (int etudiantId) throws ecole.EtudiantIntrouvable;

  // --- Bidirectionnel : C++ appelle Java pour obtenir la mention ---
  void enregistrerMentionService (ecole.MentionService svc);
  String obtenirMention (int etudiantId) throws ecole.EtudiantIntrouvable;

  // --- Bidirectionnel : C++ recherche l'etudiant, puis demande a Java d'ecrire sa fiche ---
  void enregistrerFicheService (ecole.FicheService svc);
  void genererFiche (int etudiantId) throws ecole.EtudiantIntrouvable;

  // --- Bidirectionnel : C++ demande a Java si la classe est valide avant de modifier ---
  void enregistrerValidationService (ecole.ValidationService svc);
  boolean changerClasse (int etudiantId, String nouvelleClasse) throws ecole.EtudiantIntrouvable;

  // --- Bidirectionnel : C++ demande a Java la penalite (lue dans un fichier), puis l'applique ---
  void enregistrerPenaliteService (ecole.PenaliteService svc);
  boolean appliquerPenalite (int etudiantId, String matiere) throws ecole.EtudiantIntrouvable;
} // interface GestionEtudiantsOperations
