package ecole;


/**
* ecole/ListeEtudiantsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/

public final class ListeEtudiantsHolder implements org.omg.CORBA.portable.Streamable
{
  public ecole.Etudiant value[] = null;

  public ListeEtudiantsHolder ()
  {
  }

  public ListeEtudiantsHolder (ecole.Etudiant[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ecole.ListeEtudiantsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ecole.ListeEtudiantsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ecole.ListeEtudiantsHelper.type ();
  }

}
