package ecole;


/**
* ecole/MentionServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/


// Servi par JAVA : convertit une moyenne en mention, selon un bareme lu dans un fichier.
public interface MentionServiceOperations 
{
  String calculerMention (double moyenne);
} // interface MentionServiceOperations
