package ecole;

/**
* ecole/MentionServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/


// Servi par JAVA : convertit une moyenne en mention, selon un bareme lu dans un fichier.
public final class MentionServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public ecole.MentionService value = null;

  public MentionServiceHolder ()
  {
  }

  public MentionServiceHolder (ecole.MentionService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ecole.MentionServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ecole.MentionServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ecole.MentionServiceHelper.type ();
  }

}
