package ecole;


/**
* ecole/MentionServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/


// Servi par JAVA : convertit une moyenne en mention, selon un bareme lu dans un fichier.
abstract public class MentionServiceHelper
{
  private static String  _id = "IDL:ecole/MentionService:1.0";

  public static void insert (org.omg.CORBA.Any a, ecole.MentionService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ecole.MentionService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ecole.MentionServiceHelper.id (), "MentionService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ecole.MentionService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MentionServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ecole.MentionService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ecole.MentionService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ecole.MentionService)
      return (ecole.MentionService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ecole._MentionServiceStub stub = new ecole._MentionServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ecole.MentionService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ecole.MentionService)
      return (ecole.MentionService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ecole._MentionServiceStub stub = new ecole._MentionServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
