package ecole;

/**
* ecole/PenaliteServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/


// lue dans data/penalites.txt. 0 si aucune penalite definie pour cette matiere.
public final class PenaliteServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public ecole.PenaliteService value = null;

  public PenaliteServiceHolder ()
  {
  }

  public PenaliteServiceHolder (ecole.PenaliteService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ecole.PenaliteServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ecole.PenaliteServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ecole.PenaliteServiceHelper.type ();
  }

}
