package ecole;


/**
* ecole/PenaliteServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/


// lue dans data/penalites.txt. 0 si aucune penalite definie pour cette matiere.
public abstract class PenaliteServicePOA extends org.omg.PortableServer.Servant
 implements ecole.PenaliteServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("obtenirPenalite", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ecole/PenaliteService/obtenirPenalite
       {
         String matiere = in.read_string ();
         double $result = (double)0;
         $result = this.obtenirPenalite (matiere);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ecole/PenaliteService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public PenaliteService _this() 
  {
    return PenaliteServiceHelper.narrow(
    super._this_object());
  }

  public PenaliteService _this(org.omg.CORBA.ORB orb) 
  {
    return PenaliteServiceHelper.narrow(
    super._this_object(orb));
  }


} // class PenaliteServicePOA
