package ecole;


/**
* ecole/PenaliteService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/


// lue dans data/penalites.txt. 0 si aucune penalite definie pour cette matiere.
public interface PenaliteService extends PenaliteServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PenaliteService
