package ecole;


/**
* ecole/PenaliteServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/


// lue dans data/penalites.txt. 0 si aucune penalite definie pour cette matiere.
public interface PenaliteServiceOperations 
{
  double obtenirPenalite (String matiere);
} // interface PenaliteServiceOperations
