package ecole;


/**
* ecole/PenaliteServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/


// lue dans data/penalites.txt. 0 si aucune penalite definie pour cette matiere.
abstract public class PenaliteServiceHelper
{
  private static String  _id = "IDL:ecole/PenaliteService:1.0";

  public static void insert (org.omg.CORBA.Any a, ecole.PenaliteService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ecole.PenaliteService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ecole.PenaliteServiceHelper.id (), "PenaliteService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ecole.PenaliteService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_PenaliteServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ecole.PenaliteService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ecole.PenaliteService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ecole.PenaliteService)
      return (ecole.PenaliteService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ecole._PenaliteServiceStub stub = new ecole._PenaliteServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ecole.PenaliteService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ecole.PenaliteService)
      return (ecole.PenaliteService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ecole._PenaliteServiceStub stub = new ecole._PenaliteServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
