package ecole;


/**
* ecole/ValidationService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/


// Servi par JAVA : verifie qu'un nom de classe existe dans data/classes_valides.txt.
public interface ValidationService extends ValidationServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ValidationService
