package ecole;


/**
* ecole/ValidationServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/


// Servi par JAVA : verifie qu'un nom de classe existe dans data/classes_valides.txt.
public interface ValidationServiceOperations 
{
  boolean classeValide (String nomClasse);
} // interface ValidationServiceOperations
