package ecole;

/**
* ecole/ValidationServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/


// Servi par JAVA : verifie qu'un nom de classe existe dans data/classes_valides.txt.
public final class ValidationServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public ecole.ValidationService value = null;

  public ValidationServiceHolder ()
  {
  }

  public ValidationServiceHolder (ecole.ValidationService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ecole.ValidationServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ecole.ValidationServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ecole.ValidationServiceHelper.type ();
  }

}
