package ecole;


/**
* ecole/ValidationServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../ecole.idl
* mardi 22 septembre 2026 19 h 21 EAT
*/


// Servi par JAVA : verifie qu'un nom de classe existe dans data/classes_valides.txt.
public abstract class ValidationServicePOA extends org.omg.PortableServer.Servant
 implements ecole.ValidationServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("classeValide", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ecole/ValidationService/classeValide
       {
         String nomClasse = in.read_string ();
         boolean $result = false;
         $result = this.classeValide (nomClasse);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ecole/ValidationService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ValidationService _this() 
  {
    return ValidationServiceHelper.narrow(
    super._this_object());
  }

  public ValidationService _this(org.omg.CORBA.ORB orb) 
  {
    return ValidationServiceHelper.narrow(
    super._this_object(orb));
  }


} // class ValidationServicePOA
