// This file is generated by omniidl (C++ backend)- omniORB_4_3. Do not edit.
#ifndef __ecole_hh__
#define __ecole_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_ecole
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_ecole
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_ecole
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE ecole

_CORBA_MODULE_BEG

  struct Etudiant {
    typedef _CORBA_ConstrType_Variable_Var<Etudiant> _var_type;

    
    ::CORBA::Long id;

    ::CORBA::String_member nom;

    ::CORBA::String_member prenom;

    ::CORBA::String_member classe;

  

    void operator>>= (cdrStream &) const;
    void operator<<= (cdrStream &);
  };

  typedef Etudiant::_var_type Etudiant_var;

  typedef _CORBA_ConstrType_Variable_OUT_arg< Etudiant,Etudiant_var > Etudiant_out;

  class ListeEtudiants_var;

  class ListeEtudiants : public _CORBA_Unbounded_Sequence< Etudiant >  {
  public:
    typedef ListeEtudiants_var _var_type;
    inline ListeEtudiants() {}
    inline ListeEtudiants(const ListeEtudiants& _s)
      : _CORBA_Unbounded_Sequence< Etudiant > (_s) {}

    inline ListeEtudiants(_CORBA_ULong _max)
      : _CORBA_Unbounded_Sequence< Etudiant > (_max) {}
    inline ListeEtudiants(_CORBA_ULong _max, _CORBA_ULong _len, Etudiant* _val, _CORBA_Boolean _rel=0)
      : _CORBA_Unbounded_Sequence< Etudiant > (_max, _len, _val, _rel) {}

  

    inline ListeEtudiants& operator = (const ListeEtudiants& _s) {
      _CORBA_Unbounded_Sequence< Etudiant > ::operator=(_s);
      return *this;
    }
  };

  class ListeEtudiants_out;

  class ListeEtudiants_var {
  public:
    inline ListeEtudiants_var() : _pd_seq(0) {}
    inline ListeEtudiants_var(ListeEtudiants* _s) : _pd_seq(_s) {}
    inline ListeEtudiants_var(const ListeEtudiants_var& _s) {
      if (_s._pd_seq)  _pd_seq = new ListeEtudiants(*_s._pd_seq);
      else             _pd_seq = 0;
    }
    inline ~ListeEtudiants_var() { if (_pd_seq)  delete _pd_seq; }
      
    inline ListeEtudiants_var& operator = (ListeEtudiants* _s) {
      if (_pd_seq)  delete _pd_seq;
      _pd_seq = _s;
      return *this;
    }
    inline ListeEtudiants_var& operator = (const ListeEtudiants_var& _s) {
      if (&_s != this) {
        if (_s._pd_seq) {
          if (!_pd_seq)  _pd_seq = new ListeEtudiants;
          *_pd_seq = *_s._pd_seq;
        }
        else if (_pd_seq) {
          delete _pd_seq;
          _pd_seq = 0;
        }
      }
      return *this;
    }
    inline Etudiant& operator [] (_CORBA_ULong _s) {
      return (*_pd_seq)[_s];
    }

  

    inline ListeEtudiants* operator -> () { return _pd_seq; }
    inline const ListeEtudiants* operator -> () const { return _pd_seq; }
#if defined(__GNUG__)
    inline operator ListeEtudiants& () const { return *_pd_seq; }
#else
    inline operator const ListeEtudiants& () const { return *_pd_seq; }
    inline operator ListeEtudiants& () { return *_pd_seq; }
#endif
      
    inline const ListeEtudiants& in() const { return *_pd_seq; }
    inline ListeEtudiants&       inout()    { return *_pd_seq; }
    inline ListeEtudiants*&      out() {
      if (_pd_seq) { delete _pd_seq; _pd_seq = 0; }
      return _pd_seq;
    }
    inline ListeEtudiants* _retn() { ListeEtudiants* tmp = _pd_seq; _pd_seq = 0; return tmp; }
      
    friend class ListeEtudiants_out;
    
  private:
    ListeEtudiants* _pd_seq;
  };

  class ListeEtudiants_out {
  public:
    inline ListeEtudiants_out(ListeEtudiants*& _s) : _data(_s) { _data = 0; }
    inline ListeEtudiants_out(ListeEtudiants_var& _s)
      : _data(_s._pd_seq) { _s = (ListeEtudiants*) 0; }
    inline ListeEtudiants_out(const ListeEtudiants_out& _s) : _data(_s._data) {}
    inline ListeEtudiants_out& operator = (const ListeEtudiants_out& _s) {
      _data = _s._data;
      return *this;
    }
    inline ListeEtudiants_out& operator = (ListeEtudiants* _s) {
      _data = _s;
      return *this;
    }
    inline operator ListeEtudiants*&()  { return _data; }
    inline ListeEtudiants*& ptr()       { return _data; }
    inline ListeEtudiants* operator->() { return _data; }

    inline Etudiant& operator [] (_CORBA_ULong _i) {
      return (*_data)[_i];
    }

  

    ListeEtudiants*& _data;

  private:
    ListeEtudiants_out();
    ListeEtudiants_out& operator=(const ListeEtudiants_var&);
  };

  class EtudiantIntrouvable : public ::CORBA::UserException {
  public:
    
    ::CORBA::Long id;

  

    inline EtudiantIntrouvable() {
      pd_insertToAnyFn    = insertToAnyFn;
      pd_insertToAnyFnNCP = insertToAnyFnNCP;
    }
    EtudiantIntrouvable(const EtudiantIntrouvable&);
    EtudiantIntrouvable(::CORBA::Long i_id);
    EtudiantIntrouvable& operator=(const EtudiantIntrouvable&);
    virtual ~EtudiantIntrouvable();
    virtual void _raise() const;
    static EtudiantIntrouvable* _downcast(::CORBA::Exception*);
    static const EtudiantIntrouvable* _downcast(const ::CORBA::Exception*);
    static inline EtudiantIntrouvable* _narrow(::CORBA::Exception* _e) {
      return _downcast(_e);
    }
    
    void operator>>=(cdrStream&) const ;
    void operator<<=(cdrStream&) ;

    static _core_attr insertExceptionToAny    insertToAnyFn;
    static _core_attr insertExceptionToAnyNCP insertToAnyFnNCP;

    virtual ::CORBA::Exception* _NP_duplicate() const;

    static _core_attr const char* _PD_repoId;
    static _core_attr const char* _PD_typeId;

  private:
    virtual const char* _NP_typeId() const;
    virtual const char* _NP_repoId(int*) const;
    virtual void _NP_marshal(cdrStream&) const;
  };

#ifndef __ecole_mMentionService__
#define __ecole_mMentionService__
  class MentionService;
  class _objref_MentionService;
  class _impl_MentionService;
  
  typedef _objref_MentionService* MentionService_ptr;
  typedef MentionService_ptr MentionServiceRef;

  class MentionService_Helper {
  public:
    typedef MentionService_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_MentionService, MentionService_Helper> MentionService_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_MentionService,MentionService_Helper > MentionService_out;

#endif

  // interface MentionService
  class MentionService {
  public:
    // Declarations for this interface type.
    typedef MentionService_ptr _ptr_type;
    typedef MentionService_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_MentionService :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    char* calculerMention(::CORBA::Double moyenne);

    // Constructors
    inline _objref_MentionService()  { _PR_setobj(0); }  // nil
    _objref_MentionService(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_MentionService();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_MentionService(const _objref_MentionService&);
    _objref_MentionService& operator = (const _objref_MentionService&);
    // not implemented

    friend class MentionService;
  };

  class _pof_MentionService : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_MentionService() : _OMNI_NS(proxyObjectFactory)(MentionService::_PD_repoId) {}
    virtual ~_pof_MentionService();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_MentionService :
    public virtual omniServant
  {
  public:
    virtual ~_impl_MentionService();

    virtual char* calculerMention(::CORBA::Double moyenne) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


#ifndef __ecole_mFicheService__
#define __ecole_mFicheService__
  class FicheService;
  class _objref_FicheService;
  class _impl_FicheService;
  
  typedef _objref_FicheService* FicheService_ptr;
  typedef FicheService_ptr FicheServiceRef;

  class FicheService_Helper {
  public:
    typedef FicheService_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_FicheService, FicheService_Helper> FicheService_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_FicheService,FicheService_Helper > FicheService_out;

#endif

  // interface FicheService
  class FicheService {
  public:
    // Declarations for this interface type.
    typedef FicheService_ptr _ptr_type;
    typedef FicheService_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_FicheService :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    void ecrireFiche(const ::ecole::Etudiant& e, ::CORBA::Double moyenne, const char* mention);

    // Constructors
    inline _objref_FicheService()  { _PR_setobj(0); }  // nil
    _objref_FicheService(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_FicheService();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_FicheService(const _objref_FicheService&);
    _objref_FicheService& operator = (const _objref_FicheService&);
    // not implemented

    friend class FicheService;
  };

  class _pof_FicheService : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_FicheService() : _OMNI_NS(proxyObjectFactory)(FicheService::_PD_repoId) {}
    virtual ~_pof_FicheService();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_FicheService :
    public virtual omniServant
  {
  public:
    virtual ~_impl_FicheService();

    virtual void ecrireFiche(const ::ecole::Etudiant& e, ::CORBA::Double moyenne, const char* mention) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


#ifndef __ecole_mValidationService__
#define __ecole_mValidationService__
  class ValidationService;
  class _objref_ValidationService;
  class _impl_ValidationService;
  
  typedef _objref_ValidationService* ValidationService_ptr;
  typedef ValidationService_ptr ValidationServiceRef;

  class ValidationService_Helper {
  public:
    typedef ValidationService_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_ValidationService, ValidationService_Helper> ValidationService_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_ValidationService,ValidationService_Helper > ValidationService_out;

#endif

  // interface ValidationService
  class ValidationService {
  public:
    // Declarations for this interface type.
    typedef ValidationService_ptr _ptr_type;
    typedef ValidationService_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_ValidationService :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    ::CORBA::Boolean classeValide(const char* nomClasse);

    // Constructors
    inline _objref_ValidationService()  { _PR_setobj(0); }  // nil
    _objref_ValidationService(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_ValidationService();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_ValidationService(const _objref_ValidationService&);
    _objref_ValidationService& operator = (const _objref_ValidationService&);
    // not implemented

    friend class ValidationService;
  };

  class _pof_ValidationService : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_ValidationService() : _OMNI_NS(proxyObjectFactory)(ValidationService::_PD_repoId) {}
    virtual ~_pof_ValidationService();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_ValidationService :
    public virtual omniServant
  {
  public:
    virtual ~_impl_ValidationService();

    virtual ::CORBA::Boolean classeValide(const char* nomClasse) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


#ifndef __ecole_mPenaliteService__
#define __ecole_mPenaliteService__
  class PenaliteService;
  class _objref_PenaliteService;
  class _impl_PenaliteService;
  
  typedef _objref_PenaliteService* PenaliteService_ptr;
  typedef PenaliteService_ptr PenaliteServiceRef;

  class PenaliteService_Helper {
  public:
    typedef PenaliteService_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_PenaliteService, PenaliteService_Helper> PenaliteService_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_PenaliteService,PenaliteService_Helper > PenaliteService_out;

#endif

  // interface PenaliteService
  class PenaliteService {
  public:
    // Declarations for this interface type.
    typedef PenaliteService_ptr _ptr_type;
    typedef PenaliteService_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_PenaliteService :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    ::CORBA::Double obtenirPenalite(const char* matiere);

    // Constructors
    inline _objref_PenaliteService()  { _PR_setobj(0); }  // nil
    _objref_PenaliteService(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_PenaliteService();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_PenaliteService(const _objref_PenaliteService&);
    _objref_PenaliteService& operator = (const _objref_PenaliteService&);
    // not implemented

    friend class PenaliteService;
  };

  class _pof_PenaliteService : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_PenaliteService() : _OMNI_NS(proxyObjectFactory)(PenaliteService::_PD_repoId) {}
    virtual ~_pof_PenaliteService();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_PenaliteService :
    public virtual omniServant
  {
  public:
    virtual ~_impl_PenaliteService();

    virtual ::CORBA::Double obtenirPenalite(const char* matiere) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


#ifndef __ecole_mGestionEtudiants__
#define __ecole_mGestionEtudiants__
  class GestionEtudiants;
  class _objref_GestionEtudiants;
  class _impl_GestionEtudiants;
  
  typedef _objref_GestionEtudiants* GestionEtudiants_ptr;
  typedef GestionEtudiants_ptr GestionEtudiantsRef;

  class GestionEtudiants_Helper {
  public:
    typedef GestionEtudiants_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_GestionEtudiants, GestionEtudiants_Helper> GestionEtudiants_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_GestionEtudiants,GestionEtudiants_Helper > GestionEtudiants_out;

#endif

  // interface GestionEtudiants
  class GestionEtudiants {
  public:
    // Declarations for this interface type.
    typedef GestionEtudiants_ptr _ptr_type;
    typedef GestionEtudiants_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_GestionEtudiants :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    ::CORBA::Long ajouterEtudiant(const char* nom, const char* prenom, const char* classe);
    ::CORBA::Boolean modifierEtudiant(::CORBA::Long id, const char* nom, const char* prenom, const char* classe);
    ::CORBA::Boolean supprimerEtudiant(::CORBA::Long id);
    ListeEtudiants* listerEtudiants();
    Etudiant* rechercherEtudiant(::CORBA::Long id);
    void ajouterNote(::CORBA::Long etudiantId, const char* matiere, ::CORBA::Double note);
    ::CORBA::Double calculerMoyenne(::CORBA::Long etudiantId);
    void enregistrerMentionService(::ecole::MentionService_ptr svc);
    char* obtenirMention(::CORBA::Long etudiantId);
    void enregistrerFicheService(::ecole::FicheService_ptr svc);
    void genererFiche(::CORBA::Long etudiantId);
    void enregistrerValidationService(::ecole::ValidationService_ptr svc);
    ::CORBA::Boolean changerClasse(::CORBA::Long etudiantId, const char* nouvelleClasse);
    void enregistrerPenaliteService(::ecole::PenaliteService_ptr svc);
    ::CORBA::Boolean appliquerPenalite(::CORBA::Long etudiantId, const char* matiere);

    // Constructors
    inline _objref_GestionEtudiants()  { _PR_setobj(0); }  // nil
    _objref_GestionEtudiants(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_GestionEtudiants();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_GestionEtudiants(const _objref_GestionEtudiants&);
    _objref_GestionEtudiants& operator = (const _objref_GestionEtudiants&);
    // not implemented

    friend class GestionEtudiants;
  };

  class _pof_GestionEtudiants : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_GestionEtudiants() : _OMNI_NS(proxyObjectFactory)(GestionEtudiants::_PD_repoId) {}
    virtual ~_pof_GestionEtudiants();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_GestionEtudiants :
    public virtual omniServant
  {
  public:
    virtual ~_impl_GestionEtudiants();

    virtual ::CORBA::Long ajouterEtudiant(const char* nom, const char* prenom, const char* classe) = 0;
    virtual ::CORBA::Boolean modifierEtudiant(::CORBA::Long id, const char* nom, const char* prenom, const char* classe) = 0;
    virtual ::CORBA::Boolean supprimerEtudiant(::CORBA::Long id) = 0;
    virtual ListeEtudiants* listerEtudiants() = 0;
    virtual Etudiant* rechercherEtudiant(::CORBA::Long id) = 0;
    virtual void ajouterNote(::CORBA::Long etudiantId, const char* matiere, ::CORBA::Double note) = 0;
    virtual ::CORBA::Double calculerMoyenne(::CORBA::Long etudiantId) = 0;
    virtual void enregistrerMentionService(::ecole::MentionService_ptr svc) = 0;
    virtual char* obtenirMention(::CORBA::Long etudiantId) = 0;
    virtual void enregistrerFicheService(::ecole::FicheService_ptr svc) = 0;
    virtual void genererFiche(::CORBA::Long etudiantId) = 0;
    virtual void enregistrerValidationService(::ecole::ValidationService_ptr svc) = 0;
    virtual ::CORBA::Boolean changerClasse(::CORBA::Long etudiantId, const char* nouvelleClasse) = 0;
    virtual void enregistrerPenaliteService(::ecole::PenaliteService_ptr svc) = 0;
    virtual ::CORBA::Boolean appliquerPenalite(::CORBA::Long etudiantId, const char* matiere) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_ecole
_CORBA_MODULE_BEG

  class MentionService :
    public virtual ecole::_impl_MentionService,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~MentionService();

    inline ::ecole::MentionService_ptr _this() {
      return (::ecole::MentionService_ptr) _do_this(::ecole::MentionService::_PD_repoId);
    }
  };

  class FicheService :
    public virtual ecole::_impl_FicheService,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~FicheService();

    inline ::ecole::FicheService_ptr _this() {
      return (::ecole::FicheService_ptr) _do_this(::ecole::FicheService::_PD_repoId);
    }
  };

  class ValidationService :
    public virtual ecole::_impl_ValidationService,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~ValidationService();

    inline ::ecole::ValidationService_ptr _this() {
      return (::ecole::ValidationService_ptr) _do_this(::ecole::ValidationService::_PD_repoId);
    }
  };

  class PenaliteService :
    public virtual ecole::_impl_PenaliteService,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~PenaliteService();

    inline ::ecole::PenaliteService_ptr _this() {
      return (::ecole::PenaliteService_ptr) _do_this(::ecole::PenaliteService::_PD_repoId);
    }
  };

  class GestionEtudiants :
    public virtual ecole::_impl_GestionEtudiants,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~GestionEtudiants();

    inline ::ecole::GestionEtudiants_ptr _this() {
      return (::ecole::GestionEtudiants_ptr) _do_this(::ecole::GestionEtudiants::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_ecole
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
ecole::MentionService::_marshalObjRef(::ecole::MentionService_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}

inline void
ecole::FicheService::_marshalObjRef(::ecole::FicheService_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}

inline void
ecole::ValidationService::_marshalObjRef(::ecole::ValidationService_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}

inline void
ecole::PenaliteService::_marshalObjRef(::ecole::PenaliteService_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}

inline void
ecole::GestionEtudiants::_marshalObjRef(::ecole::GestionEtudiants_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_ecole
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_ecole
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_ecole
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_ecole
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_ecole
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_ecole
#endif

#endif  // __ecole_hh__

