// This file is generated by omniidl (C++ backend) - omniORB_4_3. Do not edit.

#include "ecole.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

OMNI_MAYBE_UNUSED static const char* _0RL_library_version = omniORB_4_3;



void
ecole::Etudiant::operator>>= (cdrStream &_n) const
{
  id >>= _n;
  _n.marshalString(nom,0);
  _n.marshalString(prenom,0);
  _n.marshalString(classe,0);

}

void
ecole::Etudiant::operator<<= (cdrStream &_n)
{
  (::CORBA::Long&)id <<= _n;
  nom = _n.unmarshalString(0);
  prenom = _n.unmarshalString(0);
  classe = _n.unmarshalString(0);

}

::CORBA::Exception::insertExceptionToAny ecole::EtudiantIntrouvable::insertToAnyFn = 0;
::CORBA::Exception::insertExceptionToAnyNCP ecole::EtudiantIntrouvable::insertToAnyFnNCP = 0;

ecole::EtudiantIntrouvable::EtudiantIntrouvable(const ecole::EtudiantIntrouvable& _s) : ::CORBA::UserException(_s)
{
  id = _s.id;

}

ecole::EtudiantIntrouvable::EtudiantIntrouvable(::CORBA::Long _id)
{
  pd_insertToAnyFn    = ecole::EtudiantIntrouvable::insertToAnyFn;
  pd_insertToAnyFnNCP = ecole::EtudiantIntrouvable::insertToAnyFnNCP;
  id = _id;

}



ecole::EtudiantIntrouvable& ecole::EtudiantIntrouvable::operator=(const ecole::EtudiantIntrouvable& _s)
{
  if (&_s != this) {
    ((::CORBA::UserException*) this)->operator=(_s);
    id = _s.id;

  }
  return *this;
}

ecole::EtudiantIntrouvable::~EtudiantIntrouvable() {}

void ecole::EtudiantIntrouvable::_raise() const { throw *this; }

const char* ecole::EtudiantIntrouvable::_PD_repoId = "IDL:ecole/EtudiantIntrouvable:1.0";
const char* ecole::EtudiantIntrouvable::_PD_typeId = "Exception/UserException/ecole::EtudiantIntrouvable";

ecole::EtudiantIntrouvable* ecole::EtudiantIntrouvable::_downcast(::CORBA::Exception* _e) {
  return (EtudiantIntrouvable*) _NP_is_a(_e, _PD_typeId);
}

const ecole::EtudiantIntrouvable* ecole::EtudiantIntrouvable::_downcast(const ::CORBA::Exception* _e) {
  return (const EtudiantIntrouvable*) _NP_is_a(_e, _PD_typeId);
}

::CORBA::Exception* ecole::EtudiantIntrouvable::_NP_duplicate() const {
  return new EtudiantIntrouvable(*this);
}

const char* ecole::EtudiantIntrouvable::_NP_typeId() const {
  return _PD_typeId;
}

const char* ecole::EtudiantIntrouvable::_NP_repoId(int* _size) const {
  *_size = sizeof("IDL:ecole/EtudiantIntrouvable:1.0");
  return _PD_repoId;
}
 
void ecole::EtudiantIntrouvable::_NP_marshal(cdrStream& _s) const {
  *this >>= _s;
}

void
ecole::EtudiantIntrouvable::operator>>= (cdrStream& _n) const
{
  id >>= _n;

}

void
ecole::EtudiantIntrouvable::operator<<= (cdrStream& _n)
{
  (::CORBA::Long&)id <<= _n;

}

ecole::MentionService_ptr ecole::MentionService_Helper::_nil() {
  return ::ecole::MentionService::_nil();
}

::CORBA::Boolean ecole::MentionService_Helper::is_nil(::ecole::MentionService_ptr p) {
  return ::CORBA::is_nil(p);

}

void ecole::MentionService_Helper::release(::ecole::MentionService_ptr p) {
  ::CORBA::release(p);
}

void ecole::MentionService_Helper::marshalObjRef(::ecole::MentionService_ptr obj, cdrStream& s) {
  ::ecole::MentionService::_marshalObjRef(obj, s);
}

ecole::MentionService_ptr ecole::MentionService_Helper::unmarshalObjRef(cdrStream& s) {
  return ::ecole::MentionService::_unmarshalObjRef(s);
}

void ecole::MentionService_Helper::duplicate(::ecole::MentionService_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

ecole::MentionService_ptr
ecole::MentionService::_duplicate(::ecole::MentionService_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

ecole::MentionService_ptr
ecole::MentionService::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


ecole::MentionService_ptr
ecole::MentionService::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

ecole::MentionService_ptr
ecole::MentionService::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_MentionService _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_MentionService* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_MentionService;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* ecole::MentionService::_PD_repoId = "IDL:ecole/MentionService:1.0";


ecole::_objref_MentionService::~_objref_MentionService() {
  
}


ecole::_objref_MentionService::_objref_MentionService(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::ecole::MentionService::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
ecole::_objref_MentionService::_ptrToObjRef(const char* id)
{
  if (id == ::ecole::MentionService::_PD_repoId)
    return (::ecole::MentionService_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::ecole::MentionService::_PD_repoId))
    return (::ecole::MentionService_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for ecole::MentionService::calculerMention

// Proxy call descriptor class. Mangled signature:
//  _cstring_i_cdouble
class _0RL_cd_9d036b0306a46fca_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_9d036b0306a46fca_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Double arg_0;
  ::CORBA::String_var result;
};

void _0RL_cd_9d036b0306a46fca_00000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_9d036b0306a46fca_00000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Double&)arg_0 <<= _n;

}

void _0RL_cd_9d036b0306a46fca_00000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalString(result,0);

}

void _0RL_cd_9d036b0306a46fca_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalString(0);

}

const char* const _0RL_cd_9d036b0306a46fca_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_9d036b0306a46fca_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_9d036b0306a46fca_00000000* tcd = (_0RL_cd_9d036b0306a46fca_00000000*)cd;
  ecole::_impl_MentionService* impl = (ecole::_impl_MentionService*) svnt->_ptrToInterface(ecole::MentionService::_PD_repoId);
  tcd->result = impl->calculerMention(tcd->arg_0);


}

char* ecole::_objref_MentionService::calculerMention(::CORBA::Double moyenne)
{
  _0RL_cd_9d036b0306a46fca_00000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_10000000, "calculerMention", 16);
  _call_desc.arg_0 = moyenne;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}

ecole::_pof_MentionService::~_pof_MentionService() {}


omniObjRef*
ecole::_pof_MentionService::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::ecole::_objref_MentionService(ior, id);
}


::CORBA::Boolean
ecole::_pof_MentionService::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::ecole::MentionService::_PD_repoId))
    return 1;
  
  return 0;
}

const ecole::_pof_MentionService _the_pof_ecole_mMentionService;

ecole::_impl_MentionService::~_impl_MentionService() {}


::CORBA::Boolean
ecole::_impl_MentionService::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "calculerMention")) {

    _0RL_cd_9d036b0306a46fca_00000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_10000000, "calculerMention", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
ecole::_impl_MentionService::_ptrToInterface(const char* id)
{
  if (id == ::ecole::MentionService::_PD_repoId)
    return (::ecole::_impl_MentionService*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::ecole::MentionService::_PD_repoId))
    return (::ecole::_impl_MentionService*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
ecole::_impl_MentionService::_mostDerivedRepoId()
{
  return ::ecole::MentionService::_PD_repoId;
}

ecole::FicheService_ptr ecole::FicheService_Helper::_nil() {
  return ::ecole::FicheService::_nil();
}

::CORBA::Boolean ecole::FicheService_Helper::is_nil(::ecole::FicheService_ptr p) {
  return ::CORBA::is_nil(p);

}

void ecole::FicheService_Helper::release(::ecole::FicheService_ptr p) {
  ::CORBA::release(p);
}

void ecole::FicheService_Helper::marshalObjRef(::ecole::FicheService_ptr obj, cdrStream& s) {
  ::ecole::FicheService::_marshalObjRef(obj, s);
}

ecole::FicheService_ptr ecole::FicheService_Helper::unmarshalObjRef(cdrStream& s) {
  return ::ecole::FicheService::_unmarshalObjRef(s);
}

void ecole::FicheService_Helper::duplicate(::ecole::FicheService_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

ecole::FicheService_ptr
ecole::FicheService::_duplicate(::ecole::FicheService_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

ecole::FicheService_ptr
ecole::FicheService::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


ecole::FicheService_ptr
ecole::FicheService::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

ecole::FicheService_ptr
ecole::FicheService::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_FicheService _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_FicheService* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_FicheService;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* ecole::FicheService::_PD_repoId = "IDL:ecole/FicheService:1.0";


ecole::_objref_FicheService::~_objref_FicheService() {
  
}


ecole::_objref_FicheService::_objref_FicheService(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::ecole::FicheService::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
ecole::_objref_FicheService::_ptrToObjRef(const char* id)
{
  if (id == ::ecole::FicheService::_PD_repoId)
    return (::ecole::FicheService_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::ecole::FicheService::_PD_repoId))
    return (::ecole::FicheService_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for ecole::FicheService::ecrireFiche

// Proxy call descriptor class. Mangled signature:
//  void_i_cecole_mEtudiant_i_cdouble_i_cstring
class _0RL_cd_9d036b0306a46fca_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_9d036b0306a46fca_20000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  static const char* const _user_exns[];

  ecole::Etudiant_var arg_0_;
  const ecole::Etudiant* arg_0;
  ::CORBA::Double arg_1;
  ::CORBA::String_var arg_2_;
  const char* arg_2;
};

void _0RL_cd_9d036b0306a46fca_20000000::marshalArguments(cdrStream& _n)
{
  (const ecole::Etudiant&) *arg_0 >>= _n;
  arg_1 >>= _n;
  _n.marshalString(arg_2,0);

}

void _0RL_cd_9d036b0306a46fca_20000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = new ecole::Etudiant;
  (ecole::Etudiant&)arg_0_ <<= _n;
  arg_0 = &arg_0_.in();
  (::CORBA::Double&)arg_1 <<= _n;
  arg_2_ = _n.unmarshalString(0);
  arg_2 = arg_2_.in();

}

const char* const _0RL_cd_9d036b0306a46fca_20000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_9d036b0306a46fca_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_9d036b0306a46fca_20000000* tcd = (_0RL_cd_9d036b0306a46fca_20000000*)cd;
  ecole::_impl_FicheService* impl = (ecole::_impl_FicheService*) svnt->_ptrToInterface(ecole::FicheService::_PD_repoId);
  impl->ecrireFiche(*tcd->arg_0, tcd->arg_1, tcd->arg_2);


}

void ecole::_objref_FicheService::ecrireFiche(const ::ecole::Etudiant& e, ::CORBA::Double moyenne, const char* mention)
{
  _0RL_cd_9d036b0306a46fca_20000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_30000000, "ecrireFiche", 12);
  _call_desc.arg_0 = &(::ecole::Etudiant&) e;
  _call_desc.arg_1 = moyenne;
  _call_desc.arg_2 = mention;

  _invoke(_call_desc);



}

ecole::_pof_FicheService::~_pof_FicheService() {}


omniObjRef*
ecole::_pof_FicheService::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::ecole::_objref_FicheService(ior, id);
}


::CORBA::Boolean
ecole::_pof_FicheService::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::ecole::FicheService::_PD_repoId))
    return 1;
  
  return 0;
}

const ecole::_pof_FicheService _the_pof_ecole_mFicheService;

ecole::_impl_FicheService::~_impl_FicheService() {}


::CORBA::Boolean
ecole::_impl_FicheService::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "ecrireFiche")) {

    _0RL_cd_9d036b0306a46fca_20000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_30000000, "ecrireFiche", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
ecole::_impl_FicheService::_ptrToInterface(const char* id)
{
  if (id == ::ecole::FicheService::_PD_repoId)
    return (::ecole::_impl_FicheService*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::ecole::FicheService::_PD_repoId))
    return (::ecole::_impl_FicheService*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
ecole::_impl_FicheService::_mostDerivedRepoId()
{
  return ::ecole::FicheService::_PD_repoId;
}

ecole::ValidationService_ptr ecole::ValidationService_Helper::_nil() {
  return ::ecole::ValidationService::_nil();
}

::CORBA::Boolean ecole::ValidationService_Helper::is_nil(::ecole::ValidationService_ptr p) {
  return ::CORBA::is_nil(p);

}

void ecole::ValidationService_Helper::release(::ecole::ValidationService_ptr p) {
  ::CORBA::release(p);
}

void ecole::ValidationService_Helper::marshalObjRef(::ecole::ValidationService_ptr obj, cdrStream& s) {
  ::ecole::ValidationService::_marshalObjRef(obj, s);
}

ecole::ValidationService_ptr ecole::ValidationService_Helper::unmarshalObjRef(cdrStream& s) {
  return ::ecole::ValidationService::_unmarshalObjRef(s);
}

void ecole::ValidationService_Helper::duplicate(::ecole::ValidationService_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

ecole::ValidationService_ptr
ecole::ValidationService::_duplicate(::ecole::ValidationService_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

ecole::ValidationService_ptr
ecole::ValidationService::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


ecole::ValidationService_ptr
ecole::ValidationService::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

ecole::ValidationService_ptr
ecole::ValidationService::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_ValidationService _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_ValidationService* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_ValidationService;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* ecole::ValidationService::_PD_repoId = "IDL:ecole/ValidationService:1.0";


ecole::_objref_ValidationService::~_objref_ValidationService() {
  
}


ecole::_objref_ValidationService::_objref_ValidationService(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::ecole::ValidationService::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
ecole::_objref_ValidationService::_ptrToObjRef(const char* id)
{
  if (id == ::ecole::ValidationService::_PD_repoId)
    return (::ecole::ValidationService_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::ecole::ValidationService::_PD_repoId))
    return (::ecole::ValidationService_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for ecole::ValidationService::classeValide

// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cstring
class _0RL_cd_9d036b0306a46fca_40000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_9d036b0306a46fca_40000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::Boolean result;
};

void _0RL_cd_9d036b0306a46fca_40000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);

}

void _0RL_cd_9d036b0306a46fca_40000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();

}

void _0RL_cd_9d036b0306a46fca_40000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_9d036b0306a46fca_40000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_9d036b0306a46fca_40000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_9d036b0306a46fca_50000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_9d036b0306a46fca_40000000* tcd = (_0RL_cd_9d036b0306a46fca_40000000*)cd;
  ecole::_impl_ValidationService* impl = (ecole::_impl_ValidationService*) svnt->_ptrToInterface(ecole::ValidationService::_PD_repoId);
  tcd->result = impl->classeValide(tcd->arg_0);


}

::CORBA::Boolean ecole::_objref_ValidationService::classeValide(const char* nomClasse)
{
  _0RL_cd_9d036b0306a46fca_40000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_50000000, "classeValide", 13);
  _call_desc.arg_0 = nomClasse;

  _invoke(_call_desc);
  return _call_desc.result;


}

ecole::_pof_ValidationService::~_pof_ValidationService() {}


omniObjRef*
ecole::_pof_ValidationService::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::ecole::_objref_ValidationService(ior, id);
}


::CORBA::Boolean
ecole::_pof_ValidationService::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::ecole::ValidationService::_PD_repoId))
    return 1;
  
  return 0;
}

const ecole::_pof_ValidationService _the_pof_ecole_mValidationService;

ecole::_impl_ValidationService::~_impl_ValidationService() {}


::CORBA::Boolean
ecole::_impl_ValidationService::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "classeValide")) {

    _0RL_cd_9d036b0306a46fca_40000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_50000000, "classeValide", 13, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
ecole::_impl_ValidationService::_ptrToInterface(const char* id)
{
  if (id == ::ecole::ValidationService::_PD_repoId)
    return (::ecole::_impl_ValidationService*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::ecole::ValidationService::_PD_repoId))
    return (::ecole::_impl_ValidationService*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
ecole::_impl_ValidationService::_mostDerivedRepoId()
{
  return ::ecole::ValidationService::_PD_repoId;
}

ecole::PenaliteService_ptr ecole::PenaliteService_Helper::_nil() {
  return ::ecole::PenaliteService::_nil();
}

::CORBA::Boolean ecole::PenaliteService_Helper::is_nil(::ecole::PenaliteService_ptr p) {
  return ::CORBA::is_nil(p);

}

void ecole::PenaliteService_Helper::release(::ecole::PenaliteService_ptr p) {
  ::CORBA::release(p);
}

void ecole::PenaliteService_Helper::marshalObjRef(::ecole::PenaliteService_ptr obj, cdrStream& s) {
  ::ecole::PenaliteService::_marshalObjRef(obj, s);
}

ecole::PenaliteService_ptr ecole::PenaliteService_Helper::unmarshalObjRef(cdrStream& s) {
  return ::ecole::PenaliteService::_unmarshalObjRef(s);
}

void ecole::PenaliteService_Helper::duplicate(::ecole::PenaliteService_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

ecole::PenaliteService_ptr
ecole::PenaliteService::_duplicate(::ecole::PenaliteService_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

ecole::PenaliteService_ptr
ecole::PenaliteService::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


ecole::PenaliteService_ptr
ecole::PenaliteService::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

ecole::PenaliteService_ptr
ecole::PenaliteService::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_PenaliteService _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_PenaliteService* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_PenaliteService;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* ecole::PenaliteService::_PD_repoId = "IDL:ecole/PenaliteService:1.0";


ecole::_objref_PenaliteService::~_objref_PenaliteService() {
  
}


ecole::_objref_PenaliteService::_objref_PenaliteService(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::ecole::PenaliteService::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
ecole::_objref_PenaliteService::_ptrToObjRef(const char* id)
{
  if (id == ::ecole::PenaliteService::_PD_repoId)
    return (::ecole::PenaliteService_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::ecole::PenaliteService::_PD_repoId))
    return (::ecole::PenaliteService_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for ecole::PenaliteService::obtenirPenalite

// Proxy call descriptor class. Mangled signature:
//  _cdouble_i_cstring
class _0RL_cd_9d036b0306a46fca_60000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_9d036b0306a46fca_60000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::Double result;
};

void _0RL_cd_9d036b0306a46fca_60000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);

}

void _0RL_cd_9d036b0306a46fca_60000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();

}

void _0RL_cd_9d036b0306a46fca_60000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_9d036b0306a46fca_60000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Double&)result <<= _n;

}

const char* const _0RL_cd_9d036b0306a46fca_60000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_9d036b0306a46fca_70000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_9d036b0306a46fca_60000000* tcd = (_0RL_cd_9d036b0306a46fca_60000000*)cd;
  ecole::_impl_PenaliteService* impl = (ecole::_impl_PenaliteService*) svnt->_ptrToInterface(ecole::PenaliteService::_PD_repoId);
  tcd->result = impl->obtenirPenalite(tcd->arg_0);


}

::CORBA::Double ecole::_objref_PenaliteService::obtenirPenalite(const char* matiere)
{
  _0RL_cd_9d036b0306a46fca_60000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_70000000, "obtenirPenalite", 16);
  _call_desc.arg_0 = matiere;

  _invoke(_call_desc);
  return _call_desc.result;


}

ecole::_pof_PenaliteService::~_pof_PenaliteService() {}


omniObjRef*
ecole::_pof_PenaliteService::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::ecole::_objref_PenaliteService(ior, id);
}


::CORBA::Boolean
ecole::_pof_PenaliteService::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::ecole::PenaliteService::_PD_repoId))
    return 1;
  
  return 0;
}

const ecole::_pof_PenaliteService _the_pof_ecole_mPenaliteService;

ecole::_impl_PenaliteService::~_impl_PenaliteService() {}


::CORBA::Boolean
ecole::_impl_PenaliteService::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "obtenirPenalite")) {

    _0RL_cd_9d036b0306a46fca_60000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_70000000, "obtenirPenalite", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
ecole::_impl_PenaliteService::_ptrToInterface(const char* id)
{
  if (id == ::ecole::PenaliteService::_PD_repoId)
    return (::ecole::_impl_PenaliteService*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::ecole::PenaliteService::_PD_repoId))
    return (::ecole::_impl_PenaliteService*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
ecole::_impl_PenaliteService::_mostDerivedRepoId()
{
  return ::ecole::PenaliteService::_PD_repoId;
}

ecole::GestionEtudiants_ptr ecole::GestionEtudiants_Helper::_nil() {
  return ::ecole::GestionEtudiants::_nil();
}

::CORBA::Boolean ecole::GestionEtudiants_Helper::is_nil(::ecole::GestionEtudiants_ptr p) {
  return ::CORBA::is_nil(p);

}

void ecole::GestionEtudiants_Helper::release(::ecole::GestionEtudiants_ptr p) {
  ::CORBA::release(p);
}

void ecole::GestionEtudiants_Helper::marshalObjRef(::ecole::GestionEtudiants_ptr obj, cdrStream& s) {
  ::ecole::GestionEtudiants::_marshalObjRef(obj, s);
}

ecole::GestionEtudiants_ptr ecole::GestionEtudiants_Helper::unmarshalObjRef(cdrStream& s) {
  return ::ecole::GestionEtudiants::_unmarshalObjRef(s);
}

void ecole::GestionEtudiants_Helper::duplicate(::ecole::GestionEtudiants_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

ecole::GestionEtudiants_ptr
ecole::GestionEtudiants::_duplicate(::ecole::GestionEtudiants_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

ecole::GestionEtudiants_ptr
ecole::GestionEtudiants::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


ecole::GestionEtudiants_ptr
ecole::GestionEtudiants::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

ecole::GestionEtudiants_ptr
ecole::GestionEtudiants::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_GestionEtudiants _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_GestionEtudiants* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_GestionEtudiants;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* ecole::GestionEtudiants::_PD_repoId = "IDL:ecole/GestionEtudiants:1.0";


ecole::_objref_GestionEtudiants::~_objref_GestionEtudiants() {
  
}


ecole::_objref_GestionEtudiants::_objref_GestionEtudiants(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::ecole::GestionEtudiants::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
ecole::_objref_GestionEtudiants::_ptrToObjRef(const char* id)
{
  if (id == ::ecole::GestionEtudiants::_PD_repoId)
    return (::ecole::GestionEtudiants_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::ecole::GestionEtudiants::_PD_repoId))
    return (::ecole::GestionEtudiants_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for ecole::GestionEtudiants::ajouterEtudiant

// Proxy call descriptor class. Mangled signature:
//  _clong_i_cstring_i_cstring_i_cstring
class _0RL_cd_9d036b0306a46fca_80000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_9d036b0306a46fca_80000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::String_var arg_1_;
  const char* arg_1;
  ::CORBA::String_var arg_2_;
  const char* arg_2;
  ::CORBA::Long result;
};

void _0RL_cd_9d036b0306a46fca_80000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);
  _n.marshalString(arg_1,0);
  _n.marshalString(arg_2,0);

}

void _0RL_cd_9d036b0306a46fca_80000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();
  arg_2_ = _n.unmarshalString(0);
  arg_2 = arg_2_.in();

}

void _0RL_cd_9d036b0306a46fca_80000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_9d036b0306a46fca_80000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Long&)result <<= _n;

}

const char* const _0RL_cd_9d036b0306a46fca_80000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_9d036b0306a46fca_90000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_9d036b0306a46fca_80000000* tcd = (_0RL_cd_9d036b0306a46fca_80000000*)cd;
  ecole::_impl_GestionEtudiants* impl = (ecole::_impl_GestionEtudiants*) svnt->_ptrToInterface(ecole::GestionEtudiants::_PD_repoId);
  tcd->result = impl->ajouterEtudiant(tcd->arg_0, tcd->arg_1, tcd->arg_2);


}

::CORBA::Long ecole::_objref_GestionEtudiants::ajouterEtudiant(const char* nom, const char* prenom, const char* classe)
{
  _0RL_cd_9d036b0306a46fca_80000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_90000000, "ajouterEtudiant", 16);
  _call_desc.arg_0 = nom;
  _call_desc.arg_1 = prenom;
  _call_desc.arg_2 = classe;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for ecole::GestionEtudiants::modifierEtudiant

// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_clong_i_cstring_i_cstring_i_cstring
class _0RL_cd_9d036b0306a46fca_a0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_9d036b0306a46fca_a0000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
  ::CORBA::String_var arg_1_;
  const char* arg_1;
  ::CORBA::String_var arg_2_;
  const char* arg_2;
  ::CORBA::String_var arg_3_;
  const char* arg_3;
  ::CORBA::Boolean result;
};

void _0RL_cd_9d036b0306a46fca_a0000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  _n.marshalString(arg_1,0);
  _n.marshalString(arg_2,0);
  _n.marshalString(arg_3,0);

}

void _0RL_cd_9d036b0306a46fca_a0000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();
  arg_2_ = _n.unmarshalString(0);
  arg_2 = arg_2_.in();
  arg_3_ = _n.unmarshalString(0);
  arg_3 = arg_3_.in();

}

void _0RL_cd_9d036b0306a46fca_a0000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_9d036b0306a46fca_a0000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_9d036b0306a46fca_a0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_9d036b0306a46fca_b0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_9d036b0306a46fca_a0000000* tcd = (_0RL_cd_9d036b0306a46fca_a0000000*)cd;
  ecole::_impl_GestionEtudiants* impl = (ecole::_impl_GestionEtudiants*) svnt->_ptrToInterface(ecole::GestionEtudiants::_PD_repoId);
  tcd->result = impl->modifierEtudiant(tcd->arg_0, tcd->arg_1, tcd->arg_2, tcd->arg_3);


}

::CORBA::Boolean ecole::_objref_GestionEtudiants::modifierEtudiant(::CORBA::Long id, const char* nom, const char* prenom, const char* classe)
{
  _0RL_cd_9d036b0306a46fca_a0000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_b0000000, "modifierEtudiant", 17);
  _call_desc.arg_0 = id;
  _call_desc.arg_1 = nom;
  _call_desc.arg_2 = prenom;
  _call_desc.arg_3 = classe;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for ecole::GestionEtudiants::supprimerEtudiant

// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_clong
class _0RL_cd_9d036b0306a46fca_c0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_9d036b0306a46fca_c0000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
  ::CORBA::Boolean result;
};

void _0RL_cd_9d036b0306a46fca_c0000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_9d036b0306a46fca_c0000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;

}

void _0RL_cd_9d036b0306a46fca_c0000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_9d036b0306a46fca_c0000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_9d036b0306a46fca_c0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_9d036b0306a46fca_d0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_9d036b0306a46fca_c0000000* tcd = (_0RL_cd_9d036b0306a46fca_c0000000*)cd;
  ecole::_impl_GestionEtudiants* impl = (ecole::_impl_GestionEtudiants*) svnt->_ptrToInterface(ecole::GestionEtudiants::_PD_repoId);
  tcd->result = impl->supprimerEtudiant(tcd->arg_0);


}

::CORBA::Boolean ecole::_objref_GestionEtudiants::supprimerEtudiant(::CORBA::Long id)
{
  _0RL_cd_9d036b0306a46fca_c0000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_d0000000, "supprimerEtudiant", 18);
  _call_desc.arg_0 = id;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for ecole::GestionEtudiants::listerEtudiants

// Proxy call descriptor class. Mangled signature:
//  _cecole_mListeEtudiants
class _0RL_cd_9d036b0306a46fca_e0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_9d036b0306a46fca_e0000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ecole::ListeEtudiants_var result;
};

void _0RL_cd_9d036b0306a46fca_e0000000::marshalReturnedValues(cdrStream& _n)
{
  (const ecole::ListeEtudiants&) result >>= _n;

}

void _0RL_cd_9d036b0306a46fca_e0000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new ecole::ListeEtudiants;
  (ecole::ListeEtudiants&)result <<= _n;

}

const char* const _0RL_cd_9d036b0306a46fca_e0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_9d036b0306a46fca_f0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_9d036b0306a46fca_e0000000* tcd = (_0RL_cd_9d036b0306a46fca_e0000000*)cd;
  ecole::_impl_GestionEtudiants* impl = (ecole::_impl_GestionEtudiants*) svnt->_ptrToInterface(ecole::GestionEtudiants::_PD_repoId);
  tcd->result = impl->listerEtudiants();


}

ecole::ListeEtudiants* ecole::_objref_GestionEtudiants::listerEtudiants()
{
  _0RL_cd_9d036b0306a46fca_e0000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_f0000000, "listerEtudiants", 16);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ecole::GestionEtudiants::rechercherEtudiant

// Proxy call descriptor class. Mangled signature:
//  _cecole_mEtudiant_i_clong_e_cecole_mEtudiantIntrouvable
class _0RL_cd_9d036b0306a46fca_01000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_9d036b0306a46fca_01000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 1, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  void userException(cdrStream&, _OMNI_NS(IOP_C)*, const char*);
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
  ecole::Etudiant_var result;
};

void _0RL_cd_9d036b0306a46fca_01000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_9d036b0306a46fca_01000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;

}

void _0RL_cd_9d036b0306a46fca_01000000::marshalReturnedValues(cdrStream& _n)
{
  (const ecole::Etudiant&) result >>= _n;

}

void _0RL_cd_9d036b0306a46fca_01000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new ecole::Etudiant;
  (ecole::Etudiant&)result <<= _n;

}

const char* const _0RL_cd_9d036b0306a46fca_01000000::_user_exns[] = {
  ecole::EtudiantIntrouvable::_PD_repoId
};

void _0RL_cd_9d036b0306a46fca_01000000::userException(cdrStream& s, _OMNI_NS(IOP_C)* iop_client, const char* repoId)
{
  if (omni::strMatch(repoId, ecole::EtudiantIntrouvable::_PD_repoId)) {
    ecole::EtudiantIntrouvable _ex;
    _ex <<= s;
    if (iop_client) iop_client->RequestCompleted();
    throw _ex;
  }


  else {
    if (iop_client) iop_client->RequestCompleted(1);
    OMNIORB_THROW(UNKNOWN,UNKNOWN_UserException,
                  (::CORBA::CompletionStatus)s.completion());
  }
}

// Local call call-back function.
static void
_0RL_lcfn_9d036b0306a46fca_11000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_9d036b0306a46fca_01000000* tcd = (_0RL_cd_9d036b0306a46fca_01000000*)cd;
  ecole::_impl_GestionEtudiants* impl = (ecole::_impl_GestionEtudiants*) svnt->_ptrToInterface(ecole::GestionEtudiants::_PD_repoId);
#ifdef OMNI_HAS_Cplusplus_catch_exception_by_base
  tcd->result = impl->rechercherEtudiant(tcd->arg_0);
#else
  if (!cd->is_upcall())
    tcd->result = impl->rechercherEtudiant(tcd->arg_0);
  else {
    try {
      tcd->result = impl->rechercherEtudiant(tcd->arg_0);
    }
    catch(ecole::EtudiantIntrouvable& ex) {
      throw omniORB::StubUserException(ex._NP_duplicate());
    }


  }
#endif


}

ecole::Etudiant* ecole::_objref_GestionEtudiants::rechercherEtudiant(::CORBA::Long id)
{
  _0RL_cd_9d036b0306a46fca_01000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_11000000, "rechercherEtudiant", 19);
  _call_desc.arg_0 = id;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ecole::GestionEtudiants::ajouterNote

// Proxy call descriptor class. Mangled signature:
//  void_i_clong_i_cstring_i_cdouble
class _0RL_cd_9d036b0306a46fca_21000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_9d036b0306a46fca_21000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
  ::CORBA::String_var arg_1_;
  const char* arg_1;
  ::CORBA::Double arg_2;
};

void _0RL_cd_9d036b0306a46fca_21000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  _n.marshalString(arg_1,0);
  arg_2 >>= _n;

}

void _0RL_cd_9d036b0306a46fca_21000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();
  (::CORBA::Double&)arg_2 <<= _n;

}

const char* const _0RL_cd_9d036b0306a46fca_21000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_9d036b0306a46fca_31000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_9d036b0306a46fca_21000000* tcd = (_0RL_cd_9d036b0306a46fca_21000000*)cd;
  ecole::_impl_GestionEtudiants* impl = (ecole::_impl_GestionEtudiants*) svnt->_ptrToInterface(ecole::GestionEtudiants::_PD_repoId);
  impl->ajouterNote(tcd->arg_0, tcd->arg_1, tcd->arg_2);


}

void ecole::_objref_GestionEtudiants::ajouterNote(::CORBA::Long etudiantId, const char* matiere, ::CORBA::Double note)
{
  _0RL_cd_9d036b0306a46fca_21000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_31000000, "ajouterNote", 12);
  _call_desc.arg_0 = etudiantId;
  _call_desc.arg_1 = matiere;
  _call_desc.arg_2 = note;

  _invoke(_call_desc);



}


//
// Code for ecole::GestionEtudiants::calculerMoyenne

// Proxy call descriptor class. Mangled signature:
//  _cdouble_i_clong_e_cecole_mEtudiantIntrouvable
class _0RL_cd_9d036b0306a46fca_41000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_9d036b0306a46fca_41000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 1, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  void userException(cdrStream&, _OMNI_NS(IOP_C)*, const char*);
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
  ::CORBA::Double result;
};

void _0RL_cd_9d036b0306a46fca_41000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_9d036b0306a46fca_41000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;

}

void _0RL_cd_9d036b0306a46fca_41000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_9d036b0306a46fca_41000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Double&)result <<= _n;

}

const char* const _0RL_cd_9d036b0306a46fca_41000000::_user_exns[] = {
  ecole::EtudiantIntrouvable::_PD_repoId
};

void _0RL_cd_9d036b0306a46fca_41000000::userException(cdrStream& s, _OMNI_NS(IOP_C)* iop_client, const char* repoId)
{
  if (omni::strMatch(repoId, ecole::EtudiantIntrouvable::_PD_repoId)) {
    ecole::EtudiantIntrouvable _ex;
    _ex <<= s;
    if (iop_client) iop_client->RequestCompleted();
    throw _ex;
  }


  else {
    if (iop_client) iop_client->RequestCompleted(1);
    OMNIORB_THROW(UNKNOWN,UNKNOWN_UserException,
                  (::CORBA::CompletionStatus)s.completion());
  }
}

// Local call call-back function.
static void
_0RL_lcfn_9d036b0306a46fca_51000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_9d036b0306a46fca_41000000* tcd = (_0RL_cd_9d036b0306a46fca_41000000*)cd;
  ecole::_impl_GestionEtudiants* impl = (ecole::_impl_GestionEtudiants*) svnt->_ptrToInterface(ecole::GestionEtudiants::_PD_repoId);
#ifdef OMNI_HAS_Cplusplus_catch_exception_by_base
  tcd->result = impl->calculerMoyenne(tcd->arg_0);
#else
  if (!cd->is_upcall())
    tcd->result = impl->calculerMoyenne(tcd->arg_0);
  else {
    try {
      tcd->result = impl->calculerMoyenne(tcd->arg_0);
    }
    catch(ecole::EtudiantIntrouvable& ex) {
      throw omniORB::StubUserException(ex._NP_duplicate());
    }


  }
#endif


}

::CORBA::Double ecole::_objref_GestionEtudiants::calculerMoyenne(::CORBA::Long etudiantId)
{
  _0RL_cd_9d036b0306a46fca_41000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_51000000, "calculerMoyenne", 16);
  _call_desc.arg_0 = etudiantId;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for ecole::GestionEtudiants::enregistrerMentionService

// Proxy call descriptor class. Mangled signature:
//  void_i_cecole_mMentionService
class _0RL_cd_9d036b0306a46fca_61000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_9d036b0306a46fca_61000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  static const char* const _user_exns[];

  ecole::MentionService_var arg_0_;
  ecole::MentionService_ptr arg_0;
};

void _0RL_cd_9d036b0306a46fca_61000000::marshalArguments(cdrStream& _n)
{
  ecole::MentionService::_marshalObjRef(arg_0,_n);

}

void _0RL_cd_9d036b0306a46fca_61000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = ecole::MentionService::_unmarshalObjRef(_n);
  arg_0 = arg_0_.in();

}

const char* const _0RL_cd_9d036b0306a46fca_61000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_9d036b0306a46fca_71000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_9d036b0306a46fca_61000000* tcd = (_0RL_cd_9d036b0306a46fca_61000000*)cd;
  ecole::_impl_GestionEtudiants* impl = (ecole::_impl_GestionEtudiants*) svnt->_ptrToInterface(ecole::GestionEtudiants::_PD_repoId);
  impl->enregistrerMentionService(tcd->arg_0);


}

void ecole::_objref_GestionEtudiants::enregistrerMentionService(::ecole::MentionService_ptr svc)
{
  _0RL_cd_9d036b0306a46fca_61000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_71000000, "enregistrerMentionService", 26);
  _call_desc.arg_0 = svc;

  _invoke(_call_desc);



}


//
// Code for ecole::GestionEtudiants::obtenirMention

// Proxy call descriptor class. Mangled signature:
//  _cstring_i_clong_e_cecole_mEtudiantIntrouvable
class _0RL_cd_9d036b0306a46fca_81000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_9d036b0306a46fca_81000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 1, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  void userException(cdrStream&, _OMNI_NS(IOP_C)*, const char*);
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
  ::CORBA::String_var result;
};

void _0RL_cd_9d036b0306a46fca_81000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_9d036b0306a46fca_81000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;

}

void _0RL_cd_9d036b0306a46fca_81000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalString(result,0);

}

void _0RL_cd_9d036b0306a46fca_81000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalString(0);

}

const char* const _0RL_cd_9d036b0306a46fca_81000000::_user_exns[] = {
  ecole::EtudiantIntrouvable::_PD_repoId
};

void _0RL_cd_9d036b0306a46fca_81000000::userException(cdrStream& s, _OMNI_NS(IOP_C)* iop_client, const char* repoId)
{
  if (omni::strMatch(repoId, ecole::EtudiantIntrouvable::_PD_repoId)) {
    ecole::EtudiantIntrouvable _ex;
    _ex <<= s;
    if (iop_client) iop_client->RequestCompleted();
    throw _ex;
  }


  else {
    if (iop_client) iop_client->RequestCompleted(1);
    OMNIORB_THROW(UNKNOWN,UNKNOWN_UserException,
                  (::CORBA::CompletionStatus)s.completion());
  }
}

// Local call call-back function.
static void
_0RL_lcfn_9d036b0306a46fca_91000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_9d036b0306a46fca_81000000* tcd = (_0RL_cd_9d036b0306a46fca_81000000*)cd;
  ecole::_impl_GestionEtudiants* impl = (ecole::_impl_GestionEtudiants*) svnt->_ptrToInterface(ecole::GestionEtudiants::_PD_repoId);
#ifdef OMNI_HAS_Cplusplus_catch_exception_by_base
  tcd->result = impl->obtenirMention(tcd->arg_0);
#else
  if (!cd->is_upcall())
    tcd->result = impl->obtenirMention(tcd->arg_0);
  else {
    try {
      tcd->result = impl->obtenirMention(tcd->arg_0);
    }
    catch(ecole::EtudiantIntrouvable& ex) {
      throw omniORB::StubUserException(ex._NP_duplicate());
    }


  }
#endif


}

char* ecole::_objref_GestionEtudiants::obtenirMention(::CORBA::Long etudiantId)
{
  _0RL_cd_9d036b0306a46fca_81000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_91000000, "obtenirMention", 15);
  _call_desc.arg_0 = etudiantId;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ecole::GestionEtudiants::enregistrerFicheService

// Proxy call descriptor class. Mangled signature:
//  void_i_cecole_mFicheService
class _0RL_cd_9d036b0306a46fca_a1000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_9d036b0306a46fca_a1000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  static const char* const _user_exns[];

  ecole::FicheService_var arg_0_;
  ecole::FicheService_ptr arg_0;
};

void _0RL_cd_9d036b0306a46fca_a1000000::marshalArguments(cdrStream& _n)
{
  ecole::FicheService::_marshalObjRef(arg_0,_n);

}

void _0RL_cd_9d036b0306a46fca_a1000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = ecole::FicheService::_unmarshalObjRef(_n);
  arg_0 = arg_0_.in();

}

const char* const _0RL_cd_9d036b0306a46fca_a1000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_9d036b0306a46fca_b1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_9d036b0306a46fca_a1000000* tcd = (_0RL_cd_9d036b0306a46fca_a1000000*)cd;
  ecole::_impl_GestionEtudiants* impl = (ecole::_impl_GestionEtudiants*) svnt->_ptrToInterface(ecole::GestionEtudiants::_PD_repoId);
  impl->enregistrerFicheService(tcd->arg_0);


}

void ecole::_objref_GestionEtudiants::enregistrerFicheService(::ecole::FicheService_ptr svc)
{
  _0RL_cd_9d036b0306a46fca_a1000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_b1000000, "enregistrerFicheService", 24);
  _call_desc.arg_0 = svc;

  _invoke(_call_desc);



}


//
// Code for ecole::GestionEtudiants::genererFiche

// Proxy call descriptor class. Mangled signature:
//  void_i_clong_e_cecole_mEtudiantIntrouvable
class _0RL_cd_9d036b0306a46fca_c1000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_9d036b0306a46fca_c1000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 1, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  void userException(cdrStream&, _OMNI_NS(IOP_C)*, const char*);
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
};

void _0RL_cd_9d036b0306a46fca_c1000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_9d036b0306a46fca_c1000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;

}

const char* const _0RL_cd_9d036b0306a46fca_c1000000::_user_exns[] = {
  ecole::EtudiantIntrouvable::_PD_repoId
};

void _0RL_cd_9d036b0306a46fca_c1000000::userException(cdrStream& s, _OMNI_NS(IOP_C)* iop_client, const char* repoId)
{
  if (omni::strMatch(repoId, ecole::EtudiantIntrouvable::_PD_repoId)) {
    ecole::EtudiantIntrouvable _ex;
    _ex <<= s;
    if (iop_client) iop_client->RequestCompleted();
    throw _ex;
  }


  else {
    if (iop_client) iop_client->RequestCompleted(1);
    OMNIORB_THROW(UNKNOWN,UNKNOWN_UserException,
                  (::CORBA::CompletionStatus)s.completion());
  }
}

// Local call call-back function.
static void
_0RL_lcfn_9d036b0306a46fca_d1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_9d036b0306a46fca_c1000000* tcd = (_0RL_cd_9d036b0306a46fca_c1000000*)cd;
  ecole::_impl_GestionEtudiants* impl = (ecole::_impl_GestionEtudiants*) svnt->_ptrToInterface(ecole::GestionEtudiants::_PD_repoId);
#ifdef OMNI_HAS_Cplusplus_catch_exception_by_base
  impl->genererFiche(tcd->arg_0);
#else
  if (!cd->is_upcall())
    impl->genererFiche(tcd->arg_0);
  else {
    try {
      impl->genererFiche(tcd->arg_0);
    }
    catch(ecole::EtudiantIntrouvable& ex) {
      throw omniORB::StubUserException(ex._NP_duplicate());
    }


  }
#endif


}

void ecole::_objref_GestionEtudiants::genererFiche(::CORBA::Long etudiantId)
{
  _0RL_cd_9d036b0306a46fca_c1000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_d1000000, "genererFiche", 13);
  _call_desc.arg_0 = etudiantId;

  _invoke(_call_desc);



}


//
// Code for ecole::GestionEtudiants::enregistrerValidationService

// Proxy call descriptor class. Mangled signature:
//  void_i_cecole_mValidationService
class _0RL_cd_9d036b0306a46fca_e1000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_9d036b0306a46fca_e1000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  static const char* const _user_exns[];

  ecole::ValidationService_var arg_0_;
  ecole::ValidationService_ptr arg_0;
};

void _0RL_cd_9d036b0306a46fca_e1000000::marshalArguments(cdrStream& _n)
{
  ecole::ValidationService::_marshalObjRef(arg_0,_n);

}

void _0RL_cd_9d036b0306a46fca_e1000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = ecole::ValidationService::_unmarshalObjRef(_n);
  arg_0 = arg_0_.in();

}

const char* const _0RL_cd_9d036b0306a46fca_e1000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_9d036b0306a46fca_f1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_9d036b0306a46fca_e1000000* tcd = (_0RL_cd_9d036b0306a46fca_e1000000*)cd;
  ecole::_impl_GestionEtudiants* impl = (ecole::_impl_GestionEtudiants*) svnt->_ptrToInterface(ecole::GestionEtudiants::_PD_repoId);
  impl->enregistrerValidationService(tcd->arg_0);


}

void ecole::_objref_GestionEtudiants::enregistrerValidationService(::ecole::ValidationService_ptr svc)
{
  _0RL_cd_9d036b0306a46fca_e1000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_f1000000, "enregistrerValidationService", 29);
  _call_desc.arg_0 = svc;

  _invoke(_call_desc);



}


//
// Code for ecole::GestionEtudiants::changerClasse

// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_clong_i_cstring_e_cecole_mEtudiantIntrouvable
class _0RL_cd_9d036b0306a46fca_02000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_9d036b0306a46fca_02000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 1, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  void userException(cdrStream&, _OMNI_NS(IOP_C)*, const char*);
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
  ::CORBA::String_var arg_1_;
  const char* arg_1;
  ::CORBA::Boolean result;
};

void _0RL_cd_9d036b0306a46fca_02000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  _n.marshalString(arg_1,0);

}

void _0RL_cd_9d036b0306a46fca_02000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();

}

void _0RL_cd_9d036b0306a46fca_02000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_9d036b0306a46fca_02000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_9d036b0306a46fca_02000000::_user_exns[] = {
  ecole::EtudiantIntrouvable::_PD_repoId
};

void _0RL_cd_9d036b0306a46fca_02000000::userException(cdrStream& s, _OMNI_NS(IOP_C)* iop_client, const char* repoId)
{
  if (omni::strMatch(repoId, ecole::EtudiantIntrouvable::_PD_repoId)) {
    ecole::EtudiantIntrouvable _ex;
    _ex <<= s;
    if (iop_client) iop_client->RequestCompleted();
    throw _ex;
  }


  else {
    if (iop_client) iop_client->RequestCompleted(1);
    OMNIORB_THROW(UNKNOWN,UNKNOWN_UserException,
                  (::CORBA::CompletionStatus)s.completion());
  }
}

// Local call call-back function.
static void
_0RL_lcfn_9d036b0306a46fca_12000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_9d036b0306a46fca_02000000* tcd = (_0RL_cd_9d036b0306a46fca_02000000*)cd;
  ecole::_impl_GestionEtudiants* impl = (ecole::_impl_GestionEtudiants*) svnt->_ptrToInterface(ecole::GestionEtudiants::_PD_repoId);
#ifdef OMNI_HAS_Cplusplus_catch_exception_by_base
  tcd->result = impl->changerClasse(tcd->arg_0, tcd->arg_1);
#else
  if (!cd->is_upcall())
    tcd->result = impl->changerClasse(tcd->arg_0, tcd->arg_1);
  else {
    try {
      tcd->result = impl->changerClasse(tcd->arg_0, tcd->arg_1);
    }
    catch(ecole::EtudiantIntrouvable& ex) {
      throw omniORB::StubUserException(ex._NP_duplicate());
    }


  }
#endif


}

::CORBA::Boolean ecole::_objref_GestionEtudiants::changerClasse(::CORBA::Long etudiantId, const char* nouvelleClasse)
{
  _0RL_cd_9d036b0306a46fca_02000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_12000000, "changerClasse", 14);
  _call_desc.arg_0 = etudiantId;
  _call_desc.arg_1 = nouvelleClasse;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for ecole::GestionEtudiants::enregistrerPenaliteService

// Proxy call descriptor class. Mangled signature:
//  void_i_cecole_mPenaliteService
class _0RL_cd_9d036b0306a46fca_22000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_9d036b0306a46fca_22000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  static const char* const _user_exns[];

  ecole::PenaliteService_var arg_0_;
  ecole::PenaliteService_ptr arg_0;
};

void _0RL_cd_9d036b0306a46fca_22000000::marshalArguments(cdrStream& _n)
{
  ecole::PenaliteService::_marshalObjRef(arg_0,_n);

}

void _0RL_cd_9d036b0306a46fca_22000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = ecole::PenaliteService::_unmarshalObjRef(_n);
  arg_0 = arg_0_.in();

}

const char* const _0RL_cd_9d036b0306a46fca_22000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_9d036b0306a46fca_32000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_9d036b0306a46fca_22000000* tcd = (_0RL_cd_9d036b0306a46fca_22000000*)cd;
  ecole::_impl_GestionEtudiants* impl = (ecole::_impl_GestionEtudiants*) svnt->_ptrToInterface(ecole::GestionEtudiants::_PD_repoId);
  impl->enregistrerPenaliteService(tcd->arg_0);


}

void ecole::_objref_GestionEtudiants::enregistrerPenaliteService(::ecole::PenaliteService_ptr svc)
{
  _0RL_cd_9d036b0306a46fca_22000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_32000000, "enregistrerPenaliteService", 27);
  _call_desc.arg_0 = svc;

  _invoke(_call_desc);



}


//
// Code for ecole::GestionEtudiants::appliquerPenalite

// Local call call-back function.
static void
_0RL_lcfn_9d036b0306a46fca_42000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_9d036b0306a46fca_02000000* tcd = (_0RL_cd_9d036b0306a46fca_02000000*)cd;
  ecole::_impl_GestionEtudiants* impl = (ecole::_impl_GestionEtudiants*) svnt->_ptrToInterface(ecole::GestionEtudiants::_PD_repoId);
#ifdef OMNI_HAS_Cplusplus_catch_exception_by_base
  tcd->result = impl->appliquerPenalite(tcd->arg_0, tcd->arg_1);
#else
  if (!cd->is_upcall())
    tcd->result = impl->appliquerPenalite(tcd->arg_0, tcd->arg_1);
  else {
    try {
      tcd->result = impl->appliquerPenalite(tcd->arg_0, tcd->arg_1);
    }
    catch(ecole::EtudiantIntrouvable& ex) {
      throw omniORB::StubUserException(ex._NP_duplicate());
    }


  }
#endif


}

::CORBA::Boolean ecole::_objref_GestionEtudiants::appliquerPenalite(::CORBA::Long etudiantId, const char* matiere)
{
  _0RL_cd_9d036b0306a46fca_02000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_42000000, "appliquerPenalite", 18);
  _call_desc.arg_0 = etudiantId;
  _call_desc.arg_1 = matiere;

  _invoke(_call_desc);
  return _call_desc.result;


}

ecole::_pof_GestionEtudiants::~_pof_GestionEtudiants() {}


omniObjRef*
ecole::_pof_GestionEtudiants::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::ecole::_objref_GestionEtudiants(ior, id);
}


::CORBA::Boolean
ecole::_pof_GestionEtudiants::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::ecole::GestionEtudiants::_PD_repoId))
    return 1;
  
  return 0;
}

const ecole::_pof_GestionEtudiants _the_pof_ecole_mGestionEtudiants;

ecole::_impl_GestionEtudiants::~_impl_GestionEtudiants() {}


::CORBA::Boolean
ecole::_impl_GestionEtudiants::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "ajouterEtudiant")) {

    _0RL_cd_9d036b0306a46fca_80000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_90000000, "ajouterEtudiant", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "modifierEtudiant")) {

    _0RL_cd_9d036b0306a46fca_a0000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_b0000000, "modifierEtudiant", 17, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "supprimerEtudiant")) {

    _0RL_cd_9d036b0306a46fca_c0000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_d0000000, "supprimerEtudiant", 18, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "listerEtudiants")) {

    _0RL_cd_9d036b0306a46fca_e0000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_f0000000, "listerEtudiants", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "rechercherEtudiant")) {

    _0RL_cd_9d036b0306a46fca_01000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_11000000, "rechercherEtudiant", 19, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "ajouterNote")) {

    _0RL_cd_9d036b0306a46fca_21000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_31000000, "ajouterNote", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "calculerMoyenne")) {

    _0RL_cd_9d036b0306a46fca_41000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_51000000, "calculerMoyenne", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "enregistrerMentionService")) {

    _0RL_cd_9d036b0306a46fca_61000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_71000000, "enregistrerMentionService", 26, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "obtenirMention")) {

    _0RL_cd_9d036b0306a46fca_81000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_91000000, "obtenirMention", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "enregistrerFicheService")) {

    _0RL_cd_9d036b0306a46fca_a1000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_b1000000, "enregistrerFicheService", 24, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "genererFiche")) {

    _0RL_cd_9d036b0306a46fca_c1000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_d1000000, "genererFiche", 13, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "enregistrerValidationService")) {

    _0RL_cd_9d036b0306a46fca_e1000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_f1000000, "enregistrerValidationService", 29, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "changerClasse")) {

    _0RL_cd_9d036b0306a46fca_02000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_12000000, "changerClasse", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "enregistrerPenaliteService")) {

    _0RL_cd_9d036b0306a46fca_22000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_32000000, "enregistrerPenaliteService", 27, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "appliquerPenalite")) {

    _0RL_cd_9d036b0306a46fca_02000000 _call_desc(_0RL_lcfn_9d036b0306a46fca_42000000, "appliquerPenalite", 18, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
ecole::_impl_GestionEtudiants::_ptrToInterface(const char* id)
{
  if (id == ::ecole::GestionEtudiants::_PD_repoId)
    return (::ecole::_impl_GestionEtudiants*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::ecole::GestionEtudiants::_PD_repoId))
    return (::ecole::_impl_GestionEtudiants*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
ecole::_impl_GestionEtudiants::_mostDerivedRepoId()
{
  return ::ecole::GestionEtudiants::_PD_repoId;
}

POA_ecole::MentionService::~MentionService() {}

POA_ecole::FicheService::~FicheService() {}

POA_ecole::ValidationService::~ValidationService() {}

POA_ecole::PenaliteService::~PenaliteService() {}

POA_ecole::GestionEtudiants::~GestionEtudiants() {}

