// This file is generated by omniidl (C++ backend)- omniORB_4_3. Do not edit.
#ifndef __app_hh__
#define __app_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_app
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_app
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_app
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE chat

_CORBA_MODULE_BEG

#ifndef __chat_mNotifiable__
#define __chat_mNotifiable__
  class Notifiable;
  class _objref_Notifiable;
  class _impl_Notifiable;
  
  typedef _objref_Notifiable* Notifiable_ptr;
  typedef Notifiable_ptr NotifiableRef;

  class Notifiable_Helper {
  public:
    typedef Notifiable_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_Notifiable, Notifiable_Helper> Notifiable_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_Notifiable,Notifiable_Helper > Notifiable_out;

#endif

  // interface Notifiable
  class Notifiable {
  public:
    // Declarations for this interface type.
    typedef Notifiable_ptr _ptr_type;
    typedef Notifiable_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_Notifiable :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    void nouveauMessage(const char* auteur, const char* contenu);

    // Constructors
    inline _objref_Notifiable()  { _PR_setobj(0); }  // nil
    _objref_Notifiable(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_Notifiable();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_Notifiable(const _objref_Notifiable&);
    _objref_Notifiable& operator = (const _objref_Notifiable&);
    // not implemented

    friend class Notifiable;
  };

  class _pof_Notifiable : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_Notifiable() : _OMNI_NS(proxyObjectFactory)(Notifiable::_PD_repoId) {}
    virtual ~_pof_Notifiable();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_Notifiable :
    public virtual omniServant
  {
  public:
    virtual ~_impl_Notifiable();

    virtual void nouveauMessage(const char* auteur, const char* contenu) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


#ifndef __chat_mMessagerie__
#define __chat_mMessagerie__
  class Messagerie;
  class _objref_Messagerie;
  class _impl_Messagerie;
  
  typedef _objref_Messagerie* Messagerie_ptr;
  typedef Messagerie_ptr MessagerieRef;

  class Messagerie_Helper {
  public:
    typedef Messagerie_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_Messagerie, Messagerie_Helper> Messagerie_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_Messagerie,Messagerie_Helper > Messagerie_out;

#endif

  // interface Messagerie
  class Messagerie {
  public:
    // Declarations for this interface type.
    typedef Messagerie_ptr _ptr_type;
    typedef Messagerie_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_Messagerie :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    void envoyer(const char* auteur, const char* contenu);
    void sAbonner(::chat::Notifiable_ptr abonne);

    // Constructors
    inline _objref_Messagerie()  { _PR_setobj(0); }  // nil
    _objref_Messagerie(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_Messagerie();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_Messagerie(const _objref_Messagerie&);
    _objref_Messagerie& operator = (const _objref_Messagerie&);
    // not implemented

    friend class Messagerie;
  };

  class _pof_Messagerie : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_Messagerie() : _OMNI_NS(proxyObjectFactory)(Messagerie::_PD_repoId) {}
    virtual ~_pof_Messagerie();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_Messagerie :
    public virtual omniServant
  {
  public:
    virtual ~_impl_Messagerie();

    virtual void envoyer(const char* auteur, const char* contenu) = 0;
    virtual void sAbonner(::chat::Notifiable_ptr abonne) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_chat
_CORBA_MODULE_BEG

  class Notifiable :
    public virtual chat::_impl_Notifiable,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~Notifiable();

    inline ::chat::Notifiable_ptr _this() {
      return (::chat::Notifiable_ptr) _do_this(::chat::Notifiable::_PD_repoId);
    }
  };

  class Messagerie :
    public virtual chat::_impl_Messagerie,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~Messagerie();

    inline ::chat::Messagerie_ptr _this() {
      return (::chat::Messagerie_ptr) _do_this(::chat::Messagerie::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_chat
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
chat::Notifiable::_marshalObjRef(::chat::Notifiable_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}

inline void
chat::Messagerie::_marshalObjRef(::chat::Messagerie_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_app
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_app
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_app
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_app
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_app
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_app
#endif

#endif  // __app_hh__

