// This file is generated by omniidl (C++ backend) - omniORB_4_3. Do not edit.

#include "app.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

OMNI_MAYBE_UNUSED static const char* _0RL_library_version = omniORB_4_3;



chat::Notifiable_ptr chat::Notifiable_Helper::_nil() {
  return ::chat::Notifiable::_nil();
}

::CORBA::Boolean chat::Notifiable_Helper::is_nil(::chat::Notifiable_ptr p) {
  return ::CORBA::is_nil(p);

}

void chat::Notifiable_Helper::release(::chat::Notifiable_ptr p) {
  ::CORBA::release(p);
}

void chat::Notifiable_Helper::marshalObjRef(::chat::Notifiable_ptr obj, cdrStream& s) {
  ::chat::Notifiable::_marshalObjRef(obj, s);
}

chat::Notifiable_ptr chat::Notifiable_Helper::unmarshalObjRef(cdrStream& s) {
  return ::chat::Notifiable::_unmarshalObjRef(s);
}

void chat::Notifiable_Helper::duplicate(::chat::Notifiable_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

chat::Notifiable_ptr
chat::Notifiable::_duplicate(::chat::Notifiable_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

chat::Notifiable_ptr
chat::Notifiable::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


chat::Notifiable_ptr
chat::Notifiable::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

chat::Notifiable_ptr
chat::Notifiable::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_Notifiable _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_Notifiable* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_Notifiable;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* chat::Notifiable::_PD_repoId = "IDL:chat/Notifiable:1.0";


chat::_objref_Notifiable::~_objref_Notifiable() {
  
}


chat::_objref_Notifiable::_objref_Notifiable(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::chat::Notifiable::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
chat::_objref_Notifiable::_ptrToObjRef(const char* id)
{
  if (id == ::chat::Notifiable::_PD_repoId)
    return (::chat::Notifiable_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::chat::Notifiable::_PD_repoId))
    return (::chat::Notifiable_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for chat::Notifiable::nouveauMessage

// Proxy call descriptor class. Mangled signature:
//  void_i_cstring_i_cstring
class _0RL_cd_177e9eca42d53182_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_177e9eca42d53182_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::String_var arg_1_;
  const char* arg_1;
};

void _0RL_cd_177e9eca42d53182_00000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);
  _n.marshalString(arg_1,0);

}

void _0RL_cd_177e9eca42d53182_00000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();

}

const char* const _0RL_cd_177e9eca42d53182_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_177e9eca42d53182_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_177e9eca42d53182_00000000* tcd = (_0RL_cd_177e9eca42d53182_00000000*)cd;
  chat::_impl_Notifiable* impl = (chat::_impl_Notifiable*) svnt->_ptrToInterface(chat::Notifiable::_PD_repoId);
  impl->nouveauMessage(tcd->arg_0, tcd->arg_1);


}

void chat::_objref_Notifiable::nouveauMessage(const char* auteur, const char* contenu)
{
  _0RL_cd_177e9eca42d53182_00000000 _call_desc(_0RL_lcfn_177e9eca42d53182_10000000, "nouveauMessage", 15);
  _call_desc.arg_0 = auteur;
  _call_desc.arg_1 = contenu;

  _invoke(_call_desc);



}

chat::_pof_Notifiable::~_pof_Notifiable() {}


omniObjRef*
chat::_pof_Notifiable::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::chat::_objref_Notifiable(ior, id);
}


::CORBA::Boolean
chat::_pof_Notifiable::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::chat::Notifiable::_PD_repoId))
    return 1;
  
  return 0;
}

const chat::_pof_Notifiable _the_pof_chat_mNotifiable;

chat::_impl_Notifiable::~_impl_Notifiable() {}


::CORBA::Boolean
chat::_impl_Notifiable::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "nouveauMessage")) {

    _0RL_cd_177e9eca42d53182_00000000 _call_desc(_0RL_lcfn_177e9eca42d53182_10000000, "nouveauMessage", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
chat::_impl_Notifiable::_ptrToInterface(const char* id)
{
  if (id == ::chat::Notifiable::_PD_repoId)
    return (::chat::_impl_Notifiable*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::chat::Notifiable::_PD_repoId))
    return (::chat::_impl_Notifiable*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
chat::_impl_Notifiable::_mostDerivedRepoId()
{
  return ::chat::Notifiable::_PD_repoId;
}

chat::Messagerie_ptr chat::Messagerie_Helper::_nil() {
  return ::chat::Messagerie::_nil();
}

::CORBA::Boolean chat::Messagerie_Helper::is_nil(::chat::Messagerie_ptr p) {
  return ::CORBA::is_nil(p);

}

void chat::Messagerie_Helper::release(::chat::Messagerie_ptr p) {
  ::CORBA::release(p);
}

void chat::Messagerie_Helper::marshalObjRef(::chat::Messagerie_ptr obj, cdrStream& s) {
  ::chat::Messagerie::_marshalObjRef(obj, s);
}

chat::Messagerie_ptr chat::Messagerie_Helper::unmarshalObjRef(cdrStream& s) {
  return ::chat::Messagerie::_unmarshalObjRef(s);
}

void chat::Messagerie_Helper::duplicate(::chat::Messagerie_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

chat::Messagerie_ptr
chat::Messagerie::_duplicate(::chat::Messagerie_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

chat::Messagerie_ptr
chat::Messagerie::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


chat::Messagerie_ptr
chat::Messagerie::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

chat::Messagerie_ptr
chat::Messagerie::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_Messagerie _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_Messagerie* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_Messagerie;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* chat::Messagerie::_PD_repoId = "IDL:chat/Messagerie:1.0";


chat::_objref_Messagerie::~_objref_Messagerie() {
  
}


chat::_objref_Messagerie::_objref_Messagerie(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::chat::Messagerie::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
chat::_objref_Messagerie::_ptrToObjRef(const char* id)
{
  if (id == ::chat::Messagerie::_PD_repoId)
    return (::chat::Messagerie_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::chat::Messagerie::_PD_repoId))
    return (::chat::Messagerie_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for chat::Messagerie::envoyer

// Local call call-back function.
static void
_0RL_lcfn_177e9eca42d53182_20000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_177e9eca42d53182_00000000* tcd = (_0RL_cd_177e9eca42d53182_00000000*)cd;
  chat::_impl_Messagerie* impl = (chat::_impl_Messagerie*) svnt->_ptrToInterface(chat::Messagerie::_PD_repoId);
  impl->envoyer(tcd->arg_0, tcd->arg_1);


}

void chat::_objref_Messagerie::envoyer(const char* auteur, const char* contenu)
{
  _0RL_cd_177e9eca42d53182_00000000 _call_desc(_0RL_lcfn_177e9eca42d53182_20000000, "envoyer", 8);
  _call_desc.arg_0 = auteur;
  _call_desc.arg_1 = contenu;

  _invoke(_call_desc);



}


//
// Code for chat::Messagerie::sAbonner

// Proxy call descriptor class. Mangled signature:
//  void_i_cchat_mNotifiable
class _0RL_cd_177e9eca42d53182_30000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_177e9eca42d53182_30000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  static const char* const _user_exns[];

  chat::Notifiable_var arg_0_;
  chat::Notifiable_ptr arg_0;
};

void _0RL_cd_177e9eca42d53182_30000000::marshalArguments(cdrStream& _n)
{
  chat::Notifiable::_marshalObjRef(arg_0,_n);

}

void _0RL_cd_177e9eca42d53182_30000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = chat::Notifiable::_unmarshalObjRef(_n);
  arg_0 = arg_0_.in();

}

const char* const _0RL_cd_177e9eca42d53182_30000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_177e9eca42d53182_40000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_177e9eca42d53182_30000000* tcd = (_0RL_cd_177e9eca42d53182_30000000*)cd;
  chat::_impl_Messagerie* impl = (chat::_impl_Messagerie*) svnt->_ptrToInterface(chat::Messagerie::_PD_repoId);
  impl->sAbonner(tcd->arg_0);


}

void chat::_objref_Messagerie::sAbonner(::chat::Notifiable_ptr abonne)
{
  _0RL_cd_177e9eca42d53182_30000000 _call_desc(_0RL_lcfn_177e9eca42d53182_40000000, "sAbonner", 9);
  _call_desc.arg_0 = abonne;

  _invoke(_call_desc);



}

chat::_pof_Messagerie::~_pof_Messagerie() {}


omniObjRef*
chat::_pof_Messagerie::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::chat::_objref_Messagerie(ior, id);
}


::CORBA::Boolean
chat::_pof_Messagerie::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::chat::Messagerie::_PD_repoId))
    return 1;
  
  return 0;
}

const chat::_pof_Messagerie _the_pof_chat_mMessagerie;

chat::_impl_Messagerie::~_impl_Messagerie() {}


::CORBA::Boolean
chat::_impl_Messagerie::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "envoyer")) {

    _0RL_cd_177e9eca42d53182_00000000 _call_desc(_0RL_lcfn_177e9eca42d53182_20000000, "envoyer", 8, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "sAbonner")) {

    _0RL_cd_177e9eca42d53182_30000000 _call_desc(_0RL_lcfn_177e9eca42d53182_40000000, "sAbonner", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
chat::_impl_Messagerie::_ptrToInterface(const char* id)
{
  if (id == ::chat::Messagerie::_PD_repoId)
    return (::chat::_impl_Messagerie*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::chat::Messagerie::_PD_repoId))
    return (::chat::_impl_Messagerie*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
chat::_impl_Messagerie::_mostDerivedRepoId()
{
  return ::chat::Messagerie::_PD_repoId;
}

POA_chat::Notifiable::~Notifiable() {}

POA_chat::Messagerie::~Messagerie() {}

