// This file is generated by omniidl (C++ backend) - omniORB_4_3. Do not edit.

#include "boutique.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

OMNI_MAYBE_UNUSED static const char* _0RL_library_version = omniORB_4_3;



::CORBA::Exception::insertExceptionToAny boutique::StockInsuffisant::insertToAnyFn = 0;
::CORBA::Exception::insertExceptionToAnyNCP boutique::StockInsuffisant::insertToAnyFnNCP = 0;

boutique::StockInsuffisant::StockInsuffisant(const boutique::StockInsuffisant& _s) : ::CORBA::UserException(_s)
{
  disponible = _s.disponible;

}

boutique::StockInsuffisant::StockInsuffisant(::CORBA::Long _disponible)
{
  pd_insertToAnyFn    = boutique::StockInsuffisant::insertToAnyFn;
  pd_insertToAnyFnNCP = boutique::StockInsuffisant::insertToAnyFnNCP;
  disponible = _disponible;

}



boutique::StockInsuffisant& boutique::StockInsuffisant::operator=(const boutique::StockInsuffisant& _s)
{
  if (&_s != this) {
    ((::CORBA::UserException*) this)->operator=(_s);
    disponible = _s.disponible;

  }
  return *this;
}

boutique::StockInsuffisant::~StockInsuffisant() {}

void boutique::StockInsuffisant::_raise() const { throw *this; }

const char* boutique::StockInsuffisant::_PD_repoId = "IDL:boutique/StockInsuffisant:1.0";
const char* boutique::StockInsuffisant::_PD_typeId = "Exception/UserException/boutique::StockInsuffisant";

boutique::StockInsuffisant* boutique::StockInsuffisant::_downcast(::CORBA::Exception* _e) {
  return (StockInsuffisant*) _NP_is_a(_e, _PD_typeId);
}

const boutique::StockInsuffisant* boutique::StockInsuffisant::_downcast(const ::CORBA::Exception* _e) {
  return (const StockInsuffisant*) _NP_is_a(_e, _PD_typeId);
}

::CORBA::Exception* boutique::StockInsuffisant::_NP_duplicate() const {
  return new StockInsuffisant(*this);
}

const char* boutique::StockInsuffisant::_NP_typeId() const {
  return _PD_typeId;
}

const char* boutique::StockInsuffisant::_NP_repoId(int* _size) const {
  *_size = sizeof("IDL:boutique/StockInsuffisant:1.0");
  return _PD_repoId;
}
 
void boutique::StockInsuffisant::_NP_marshal(cdrStream& _s) const {
  *this >>= _s;
}

void
boutique::StockInsuffisant::operator>>= (cdrStream& _n) const
{
  disponible >>= _n;

}

void
boutique::StockInsuffisant::operator<<= (cdrStream& _n)
{
  (::CORBA::Long&)disponible <<= _n;

}

boutique::Commande_ptr boutique::Commande_Helper::_nil() {
  return ::boutique::Commande::_nil();
}

::CORBA::Boolean boutique::Commande_Helper::is_nil(::boutique::Commande_ptr p) {
  return ::CORBA::is_nil(p);

}

void boutique::Commande_Helper::release(::boutique::Commande_ptr p) {
  ::CORBA::release(p);
}

void boutique::Commande_Helper::marshalObjRef(::boutique::Commande_ptr obj, cdrStream& s) {
  ::boutique::Commande::_marshalObjRef(obj, s);
}

boutique::Commande_ptr boutique::Commande_Helper::unmarshalObjRef(cdrStream& s) {
  return ::boutique::Commande::_unmarshalObjRef(s);
}

void boutique::Commande_Helper::duplicate(::boutique::Commande_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

boutique::Commande_ptr
boutique::Commande::_duplicate(::boutique::Commande_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

boutique::Commande_ptr
boutique::Commande::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


boutique::Commande_ptr
boutique::Commande::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

boutique::Commande_ptr
boutique::Commande::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_Commande _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_Commande* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_Commande;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* boutique::Commande::_PD_repoId = "IDL:boutique/Commande:1.0";


boutique::_objref_Commande::~_objref_Commande() {
  
}


boutique::_objref_Commande::_objref_Commande(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::boutique::Commande::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
boutique::_objref_Commande::_ptrToObjRef(const char* id)
{
  if (id == ::boutique::Commande::_PD_repoId)
    return (::boutique::Commande_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::boutique::Commande::_PD_repoId))
    return (::boutique::Commande_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for boutique::Commande::quantiteDemandee

// Proxy call descriptor class. Mangled signature:
//  _clong_i_cstring
class _0RL_cd_6916e5dfd5aeef77_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_6916e5dfd5aeef77_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::Long result;
};

void _0RL_cd_6916e5dfd5aeef77_00000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);

}

void _0RL_cd_6916e5dfd5aeef77_00000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();

}

void _0RL_cd_6916e5dfd5aeef77_00000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_6916e5dfd5aeef77_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Long&)result <<= _n;

}

const char* const _0RL_cd_6916e5dfd5aeef77_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_6916e5dfd5aeef77_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_6916e5dfd5aeef77_00000000* tcd = (_0RL_cd_6916e5dfd5aeef77_00000000*)cd;
  boutique::_impl_Commande* impl = (boutique::_impl_Commande*) svnt->_ptrToInterface(boutique::Commande::_PD_repoId);
  tcd->result = impl->quantiteDemandee(tcd->arg_0);


}

::CORBA::Long boutique::_objref_Commande::quantiteDemandee(const char* produit)
{
  _0RL_cd_6916e5dfd5aeef77_00000000 _call_desc(_0RL_lcfn_6916e5dfd5aeef77_10000000, "quantiteDemandee", 17);
  _call_desc.arg_0 = produit;

  _invoke(_call_desc);
  return _call_desc.result;


}

boutique::_pof_Commande::~_pof_Commande() {}


omniObjRef*
boutique::_pof_Commande::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::boutique::_objref_Commande(ior, id);
}


::CORBA::Boolean
boutique::_pof_Commande::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::boutique::Commande::_PD_repoId))
    return 1;
  
  return 0;
}

const boutique::_pof_Commande _the_pof_boutique_mCommande;

boutique::_impl_Commande::~_impl_Commande() {}


::CORBA::Boolean
boutique::_impl_Commande::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "quantiteDemandee")) {

    _0RL_cd_6916e5dfd5aeef77_00000000 _call_desc(_0RL_lcfn_6916e5dfd5aeef77_10000000, "quantiteDemandee", 17, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
boutique::_impl_Commande::_ptrToInterface(const char* id)
{
  if (id == ::boutique::Commande::_PD_repoId)
    return (::boutique::_impl_Commande*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::boutique::Commande::_PD_repoId))
    return (::boutique::_impl_Commande*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
boutique::_impl_Commande::_mostDerivedRepoId()
{
  return ::boutique::Commande::_PD_repoId;
}

boutique::Stock_ptr boutique::Stock_Helper::_nil() {
  return ::boutique::Stock::_nil();
}

::CORBA::Boolean boutique::Stock_Helper::is_nil(::boutique::Stock_ptr p) {
  return ::CORBA::is_nil(p);

}

void boutique::Stock_Helper::release(::boutique::Stock_ptr p) {
  ::CORBA::release(p);
}

void boutique::Stock_Helper::marshalObjRef(::boutique::Stock_ptr obj, cdrStream& s) {
  ::boutique::Stock::_marshalObjRef(obj, s);
}

boutique::Stock_ptr boutique::Stock_Helper::unmarshalObjRef(cdrStream& s) {
  return ::boutique::Stock::_unmarshalObjRef(s);
}

void boutique::Stock_Helper::duplicate(::boutique::Stock_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

boutique::Stock_ptr
boutique::Stock::_duplicate(::boutique::Stock_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

boutique::Stock_ptr
boutique::Stock::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


boutique::Stock_ptr
boutique::Stock::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

boutique::Stock_ptr
boutique::Stock::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_Stock _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_Stock* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_Stock;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* boutique::Stock::_PD_repoId = "IDL:boutique/Stock:1.0";


boutique::_objref_Stock::~_objref_Stock() {
  
}


boutique::_objref_Stock::_objref_Stock(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::boutique::Stock::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
boutique::_objref_Stock::_ptrToObjRef(const char* id)
{
  if (id == ::boutique::Stock::_PD_repoId)
    return (::boutique::Stock_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::boutique::Stock::_PD_repoId))
    return (::boutique::Stock_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for boutique::Stock::acheter

// Proxy call descriptor class. Mangled signature:
//  _clong_i_cstring_e_cboutique_mStockInsuffisant
class _0RL_cd_6916e5dfd5aeef77_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_6916e5dfd5aeef77_20000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 1, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  void userException(cdrStream&, _OMNI_NS(IOP_C)*, const char*);
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::Long result;
};

void _0RL_cd_6916e5dfd5aeef77_20000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);

}

void _0RL_cd_6916e5dfd5aeef77_20000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();

}

void _0RL_cd_6916e5dfd5aeef77_20000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_6916e5dfd5aeef77_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Long&)result <<= _n;

}

const char* const _0RL_cd_6916e5dfd5aeef77_20000000::_user_exns[] = {
  boutique::StockInsuffisant::_PD_repoId
};

void _0RL_cd_6916e5dfd5aeef77_20000000::userException(cdrStream& s, _OMNI_NS(IOP_C)* iop_client, const char* repoId)
{
  if (omni::strMatch(repoId, boutique::StockInsuffisant::_PD_repoId)) {
    boutique::StockInsuffisant _ex;
    _ex <<= s;
    if (iop_client) iop_client->RequestCompleted();
    throw _ex;
  }


  else {
    if (iop_client) iop_client->RequestCompleted(1);
    OMNIORB_THROW(UNKNOWN,UNKNOWN_UserException,
                  (::CORBA::CompletionStatus)s.completion());
  }
}

// Local call call-back function.
static void
_0RL_lcfn_6916e5dfd5aeef77_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_6916e5dfd5aeef77_20000000* tcd = (_0RL_cd_6916e5dfd5aeef77_20000000*)cd;
  boutique::_impl_Stock* impl = (boutique::_impl_Stock*) svnt->_ptrToInterface(boutique::Stock::_PD_repoId);
#ifdef OMNI_HAS_Cplusplus_catch_exception_by_base
  tcd->result = impl->acheter(tcd->arg_0);
#else
  if (!cd->is_upcall())
    tcd->result = impl->acheter(tcd->arg_0);
  else {
    try {
      tcd->result = impl->acheter(tcd->arg_0);
    }
    catch(boutique::StockInsuffisant& ex) {
      throw omniORB::StubUserException(ex._NP_duplicate());
    }


  }
#endif


}

::CORBA::Long boutique::_objref_Stock::acheter(const char* produit)
{
  _0RL_cd_6916e5dfd5aeef77_20000000 _call_desc(_0RL_lcfn_6916e5dfd5aeef77_30000000, "acheter", 8);
  _call_desc.arg_0 = produit;

  _invoke(_call_desc);
  return _call_desc.result;


}

boutique::_pof_Stock::~_pof_Stock() {}


omniObjRef*
boutique::_pof_Stock::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::boutique::_objref_Stock(ior, id);
}


::CORBA::Boolean
boutique::_pof_Stock::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::boutique::Stock::_PD_repoId))
    return 1;
  
  return 0;
}

const boutique::_pof_Stock _the_pof_boutique_mStock;

boutique::_impl_Stock::~_impl_Stock() {}


::CORBA::Boolean
boutique::_impl_Stock::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "acheter")) {

    _0RL_cd_6916e5dfd5aeef77_20000000 _call_desc(_0RL_lcfn_6916e5dfd5aeef77_30000000, "acheter", 8, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
boutique::_impl_Stock::_ptrToInterface(const char* id)
{
  if (id == ::boutique::Stock::_PD_repoId)
    return (::boutique::_impl_Stock*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::boutique::Stock::_PD_repoId))
    return (::boutique::_impl_Stock*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
boutique::_impl_Stock::_mostDerivedRepoId()
{
  return ::boutique::Stock::_PD_repoId;
}

POA_boutique::Commande::~Commande() {}

POA_boutique::Stock::~Stock() {}

