// This file is generated by omniidl (C++ backend)- omniORB_4_3. Do not edit.
#ifndef __boutique_hh__
#define __boutique_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_boutique
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_boutique
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_boutique
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE boutique

_CORBA_MODULE_BEG

  class StockInsuffisant : public ::CORBA::UserException {
  public:
    
    ::CORBA::Long disponible;

  

    inline StockInsuffisant() {
      pd_insertToAnyFn    = insertToAnyFn;
      pd_insertToAnyFnNCP = insertToAnyFnNCP;
    }
    StockInsuffisant(const StockInsuffisant&);
    StockInsuffisant(::CORBA::Long i_disponible);
    StockInsuffisant& operator=(const StockInsuffisant&);
    virtual ~StockInsuffisant();
    virtual void _raise() const;
    static StockInsuffisant* _downcast(::CORBA::Exception*);
    static const StockInsuffisant* _downcast(const ::CORBA::Exception*);
    static inline StockInsuffisant* _narrow(::CORBA::Exception* _e) {
      return _downcast(_e);
    }
    
    void operator>>=(cdrStream&) const ;
    void operator<<=(cdrStream&) ;

    static _core_attr insertExceptionToAny    insertToAnyFn;
    static _core_attr insertExceptionToAnyNCP insertToAnyFnNCP;

    virtual ::CORBA::Exception* _NP_duplicate() const;

    static _core_attr const char* _PD_repoId;
    static _core_attr const char* _PD_typeId;

  private:
    virtual const char* _NP_typeId() const;
    virtual const char* _NP_repoId(int*) const;
    virtual void _NP_marshal(cdrStream&) const;
  };

#ifndef __boutique_mCommande__
#define __boutique_mCommande__
  class Commande;
  class _objref_Commande;
  class _impl_Commande;
  
  typedef _objref_Commande* Commande_ptr;
  typedef Commande_ptr CommandeRef;

  class Commande_Helper {
  public:
    typedef Commande_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_Commande, Commande_Helper> Commande_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_Commande,Commande_Helper > Commande_out;

#endif

  // interface Commande
  class Commande {
  public:
    // Declarations for this interface type.
    typedef Commande_ptr _ptr_type;
    typedef Commande_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_Commande :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    ::CORBA::Long quantiteDemandee(const char* produit);

    // Constructors
    inline _objref_Commande()  { _PR_setobj(0); }  // nil
    _objref_Commande(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_Commande();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_Commande(const _objref_Commande&);
    _objref_Commande& operator = (const _objref_Commande&);
    // not implemented

    friend class Commande;
  };

  class _pof_Commande : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_Commande() : _OMNI_NS(proxyObjectFactory)(Commande::_PD_repoId) {}
    virtual ~_pof_Commande();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_Commande :
    public virtual omniServant
  {
  public:
    virtual ~_impl_Commande();

    virtual ::CORBA::Long quantiteDemandee(const char* produit) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


#ifndef __boutique_mStock__
#define __boutique_mStock__
  class Stock;
  class _objref_Stock;
  class _impl_Stock;
  
  typedef _objref_Stock* Stock_ptr;
  typedef Stock_ptr StockRef;

  class Stock_Helper {
  public:
    typedef Stock_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_Stock, Stock_Helper> Stock_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_Stock,Stock_Helper > Stock_out;

#endif

  // interface Stock
  class Stock {
  public:
    // Declarations for this interface type.
    typedef Stock_ptr _ptr_type;
    typedef Stock_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_Stock :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    ::CORBA::Long acheter(const char* produit);

    // Constructors
    inline _objref_Stock()  { _PR_setobj(0); }  // nil
    _objref_Stock(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_Stock();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_Stock(const _objref_Stock&);
    _objref_Stock& operator = (const _objref_Stock&);
    // not implemented

    friend class Stock;
  };

  class _pof_Stock : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_Stock() : _OMNI_NS(proxyObjectFactory)(Stock::_PD_repoId) {}
    virtual ~_pof_Stock();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_Stock :
    public virtual omniServant
  {
  public:
    virtual ~_impl_Stock();

    virtual ::CORBA::Long acheter(const char* produit) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_boutique
_CORBA_MODULE_BEG

  class Commande :
    public virtual boutique::_impl_Commande,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~Commande();

    inline ::boutique::Commande_ptr _this() {
      return (::boutique::Commande_ptr) _do_this(::boutique::Commande::_PD_repoId);
    }
  };

  class Stock :
    public virtual boutique::_impl_Stock,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~Stock();

    inline ::boutique::Stock_ptr _this() {
      return (::boutique::Stock_ptr) _do_this(::boutique::Stock::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_boutique
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
boutique::Commande::_marshalObjRef(::boutique::Commande_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}

inline void
boutique::Stock::_marshalObjRef(::boutique::Stock_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_boutique
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_boutique
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_boutique
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_boutique
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_boutique
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_boutique
#endif

#endif  // __boutique_hh__

